### Load relevant libraries

In [41]:
import os
import pandas as pd
pd.set_option('display.max_columns', None)

from functools import reduce

### Read in the data

In [42]:
# Set working directory (necessary until 2019 data comes out)
path = 'C:/Users/caanm/OneDrive/Documents/Project Portfolio/March Madness 2026/2026 Data'
os.chdir(path)

In [43]:
# Read in Sample Submission datasets
SampleSubmission_p1 = pd.read_csv('SampleSubmissionStage1.csv', sep=',', index_col=None)
SampleSubmission_p2 = pd.read_csv('SampleSubmissionStage2.csv', sep=',', index_col=None)

In [44]:
# Read in Mens datasets
M_TourneySeeds = pd.read_csv('MNCAATourneySeeds.csv', sep=',', index_col=None)
M_Seasons = pd.read_csv('MSeasons.csv', sep=',', index_col=None)
M_Teams = pd.read_csv('MTeams.csv', sep=',', index_col=None)
M_TourneySlots = pd.read_csv('MNCAATourneySlots.csv', sep=',', index_col=None)
M_TourneyDetailedResults = pd.read_csv('MNCAATourneyDetailedResults.csv', sep=',', index_col=None)
M_TourneyCompactResults = pd.read_csv('MNCAATourneyCompactResults.csv', sep=',', index_col=None)
M_RegularDetailedResults = pd.read_csv('MRegularSeasonDetailedResults.csv', sep=',', index_col=None)
M_RegularCompactResults = pd.read_csv('MRegularSeasonCompactResults.csv', sep=',', index_col=None)
M_TeamConf = pd.read_csv('MTeamConferences.csv', sep=',', index_col=None)

# Supplemental data: Conference Rankings from barttorvik.com
M_ConfRank = pd.read_csv('MConference_Rankings barttorvik.com.csv', sep=',', index_col=None)

In [45]:
# Read in Womens datasets
W_TourneySeeds = pd.read_csv('WNCAATourneySeeds.csv', sep=',', index_col=None)
W_Seasons = pd.read_csv('WSeasons.csv', sep=',', index_col=None)
W_Teams = pd.read_csv('WTeams.csv', sep=',', index_col=None)
W_TourneySlots = pd.read_csv('WNCAATourneySlots.csv', sep=',', index_col=None)
W_TourneyDetailedResults = pd.read_csv('WNCAATourneyDetailedResults.csv', sep=',', index_col=None)
W_TourneyCompactResults = pd.read_csv('WNCAATourneyCompactResults.csv', sep=',', index_col=None)
W_RegularDetailedResults = pd.read_csv('WRegularSeasonDetailedResults.csv', sep=',', index_col=None)
W_RegularCompactResults = pd.read_csv('WRegularSeasonCompactResults.csv', sep=',', index_col=None)
W_TeamConf = pd.read_csv('WTeamConferences.csv', sep=',', index_col=None)

# Supplemental data: Conference Rankings from barttorvik.com
W_ConfRank = pd.read_csv('WConference_Rankings barttorvik.com.csv', sep=',', index_col=None)

In [46]:
# Merge Mens and Womens datasets
SampleSubmission = pd.concat([SampleSubmission_p1,SampleSubmission_p2]).drop_duplicates()
TourneySeeds = pd.concat([M_TourneySeeds,W_TourneySeeds])
Seasons = pd.concat([M_Seasons,W_Seasons])
Teams = pd.concat([M_Teams,W_Teams])
TourneySlots = pd.concat([M_TourneySlots,W_TourneySlots])
TourneyDetailedResults = pd.concat([M_TourneyDetailedResults,W_TourneyDetailedResults])
TourneyCompactResults = pd.concat([M_TourneyCompactResults,W_TourneyCompactResults])
RegularDetailedResults = pd.concat([M_RegularDetailedResults,W_RegularDetailedResults])
RegularCompactResults = pd.concat([M_RegularCompactResults,W_RegularCompactResults])
TeamConf = pd.concat([M_TeamConf,W_TeamConf])
ConfRank = pd.concat([M_ConfRank,W_ConfRank])

### Summarize data

In [57]:
# Check datasets to make sure read worked
display(TourneySeeds.head())
display(SampleSubmission.head())
display(Seasons.head())
display(Teams.head())
display(TourneySlots.head())
display(TourneyDetailedResults.head())
display(TourneyCompactResults.head())
display(RegularDetailedResults.head())
display(RegularCompactResults.head())
display(TeamConf.head())
display(ConfRank.head())

   Season Seed  TeamID
0    1985  W01    1207
1    1985  W02    1210
2    1985  W03    1228
3    1985  W04    1260
4    1985  W05    1374

               ID  Pred
0  2022_1101_1102   0.5
1  2022_1101_1103   0.5
2  2022_1101_1104   0.5
3  2022_1101_1105   0.5
4  2022_1101_1106   0.5

   Season     DayZero RegionW    RegionX    RegionY    RegionZ
0    1985  10/29/1984    East       West    Midwest  Southeast
1    1986  10/28/1985    East    Midwest  Southeast       West
2    1987  10/27/1986    East  Southeast    Midwest       West
3    1988  11/02/1987    East    Midwest  Southeast       West
4    1989  10/31/1988    East       West    Midwest  Southeast

   TeamID     TeamName  FirstD1Season  LastD1Season
0    1101  Abilene Chr         2014.0        2026.0
1    1102    Air Force         1985.0        2026.0
2    1103        Akron         1985.0        2026.0
3    1104      Alabama         1985.0        2026.0
4    1105  Alabama A&M         2000.0        2026.0

   Season  Slot StrongSeed WeakSeed
0    1985  R1W1        W01      W16
1    1985  R1W2        W02      W15
2    1985  R1W3        W03      W14
3    1985  R1W4        W04      W13
4    1985  R1W5        W05      W12

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,WFGM3,WFGA3,WFTM,WFTA,WOR,WDR,WAst,WTO,WStl,WBlk,WPF,LFGM,LFGA,LFGM3,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,134,1421,92,1411,84,N,1,32,69,11,29,17,26,14,30,17,12,5,3,22,29,67,12,31,14,31,17,28,16,15,5,0,22
1,2003,136,1112,80,1436,51,N,0,31,66,7,23,11,14,11,36,22,16,10,7,8,20,64,4,16,7,7,8,26,12,17,10,3,15
2,2003,136,1113,84,1272,71,N,0,31,59,6,14,16,22,10,27,18,9,7,4,19,25,69,7,28,14,21,20,22,11,12,2,5,18
3,2003,136,1141,79,1166,73,N,0,29,53,3,7,18,25,11,20,15,18,13,1,19,27,60,7,17,12,17,14,17,20,21,6,6,21
4,2003,136,1143,76,1301,74,N,1,27,64,7,20,15,23,18,20,17,13,8,2,14,25,56,9,21,15,20,10,26,16,14,5,8,19

   Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1985     136     1116      63     1234      54    N      0
1    1985     136     1120      59     1345      58    N      0
2    1985     136     1207      68     1250      43    N      0
3    1985     136     1229      58     1425      55    N      0
4    1985     136     1242      49     1325      38    N      0

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,WFGM3,WFGA3,WFTM,WFTA,WOR,WDR,WAst,WTO,WStl,WBlk,WPF,LFGM,LFGA,LFGM3,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,10,1104,68,1328,62,N,0,27,58,3,14,11,18,14,24,13,23,7,1,22,22,53,2,10,16,22,10,22,8,18,9,2,20
1,2003,10,1272,70,1393,63,N,0,26,62,8,20,10,19,15,28,16,13,4,4,18,24,67,6,24,9,20,20,25,7,12,8,6,16
2,2003,11,1266,73,1437,61,N,0,24,58,8,18,17,29,17,26,15,10,5,2,25,22,73,3,26,14,23,31,22,9,12,2,5,23
3,2003,11,1296,56,1457,50,N,0,18,38,3,9,17,31,6,19,11,12,14,2,18,18,49,6,22,8,15,17,20,9,19,4,3,23
4,2003,11,1400,77,1208,71,N,0,30,61,6,14,11,13,17,22,12,14,4,4,20,24,62,6,16,17,27,21,15,12,10,7,1,14

   Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1985      20     1228      81     1328      64    N      0
1    1985      25     1106      77     1354      70    H      0
2    1985      25     1112      63     1223      56    H      0
3    1985      25     1165      70     1432      54    H      0
4    1985      25     1192      86     1447      74    H      0

   Season  TeamID ConfAbbrev
0    1985    1102        wac
1    1985    1103        ovc
2    1985    1104        sec
3    1985    1106       swac
4    1985    1108       swac

   Rank Conference  season        conf M_W
0     1        SEC    2026         sec   M
1     2        B10    2026     big_ten   M
2     3        B12    2026  big_twelve   M
3     4        ACC    2026         acc   M
4     5         BE    2026    big_east   M

In [8]:
# Describe relevant datasets
display(TourneySeeds.describe(include = 'all'))
display(SampleSubmission.describe(include = 'all'))
display(Seasons.describe(include = 'all'))
display(Teams.describe(include = 'all'))
display(TourneySlots.describe(include = 'all'))
display(TourneyDetailedResults.describe(include = 'all'))
display(TourneyCompactResults.describe(include = 'all'))
display(RegularDetailedResults.describe(include = 'all'))
display(RegularCompactResults.describe(include = 'all'))
display(TeamConf.describe(include = 'all'))
display(ConfRank.describe(include = 'all'))

             Season  Seed       TeamID
count   4506.000000  4506  4506.000000
unique          NaN    98          NaN
top             NaN   W01          NaN
freq            NaN    69          NaN
mean    2008.019308   NaN  2094.000222
std       11.209233   NaN   984.626332
min     1985.000000   NaN  1101.000000
25%     2000.000000   NaN  1266.000000
50%     2009.000000   NaN  1412.500000
75%     2017.000000   NaN  3251.000000
max     2026.000000   NaN  3471.000000

                    ID      Pred
count           651277  651277.0
unique          651277       NaN
top     2022_1101_1102       NaN
freq                 1       NaN
mean               NaN       0.5
std                NaN       0.0
min                NaN       0.5
25%                NaN       0.5
50%                NaN       0.5
75%                NaN       0.5
max                NaN       0.5

             Season     DayZero RegionW  RegionX  RegionY RegionZ
count     71.000000          71      71       71       71      71
unique          NaN          42      18       25       23      27
top             NaN  10/31/2005    East  Midwest  Midwest    West
freq            NaN           2      45       15       27      31
mean    2008.154930         NaN     NaN      NaN      NaN     NaN
std       11.291777         NaN     NaN      NaN      NaN     NaN
min     1985.000000         NaN     NaN      NaN      NaN     NaN
25%     2000.000000         NaN     NaN      NaN      NaN     NaN
50%     2009.000000         NaN     NaN      NaN      NaN     NaN
75%     2017.500000         NaN     NaN      NaN      NaN     NaN
max     2026.000000         NaN     NaN      NaN      NaN     NaN

             TeamID     TeamName  FirstD1Season  LastD1Season
count    760.000000          760     381.000000    381.000000
unique          NaN          381            NaN           NaN
top             NaN  Abilene Chr            NaN           NaN
freq            NaN            2            NaN           NaN
mean    2288.352632          NaN    1989.713911   2024.913386
std     1006.662498          NaN       9.919653      5.857101
min     1101.000000          NaN    1985.000000   1985.000000
25%     1290.750000          NaN    1985.000000   2026.000000
50%     1480.500000          NaN    1985.000000   2026.000000
75%     3290.250000          NaN    1987.000000   2026.000000
max     3481.000000          NaN    2026.000000   2026.000000

             Season  Slot StrongSeed WeakSeed
count   4500.000000  4500       4500     4500
unique          NaN    80         80       80
top             NaN  R1W1        W01      W16
freq            NaN    70         70       70
mean    2008.190222   NaN        NaN      NaN
std       11.219398   NaN        NaN      NaN
min     1985.000000   NaN        NaN      NaN
25%     2000.000000   NaN        NaN      NaN
50%     2009.000000   NaN        NaN      NaN
75%     2017.000000   NaN        NaN      NaN
max     2026.000000   NaN        NaN      NaN

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,WFGM3,WFGA3,WFTM,WFTA,WOR,WDR,WAst,WTO,WStl,WBlk,WPF,LFGM,LFGA,LFGM3,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
count,2410.000000,2410.000000,2410.000000,2410.000000,2410.00000,2410.000000,2410,2410.000000,2410.000000,2410.000000,2410.000000,2410.000000,2410.000000,2410.000000,2410.000000,2410.000000,2410.000000,2410.000000,2410.000000,2410.00000,2410.000000,2410.000000,2410.000000,2410.000000,2410.000000,2410.000000,2410.000000,2410.000000,2410.000000,2410.000000,2410.000000,2410.000000,2410.000000,2410.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,2031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,2015.275104,139.660166,2084.074274,75.941079,2087.00249,62.089627,NaN,0.053527,27.115768,57.687552,6.788382,18.038589,14.921162,20.381328,10.947303,26.558506,15.055602,11.987967,6.953527,4.23278,15.622407,22.621577,59.180913,5.980083,20.324066,10.866390,15.412033,10.781328,21.269295,11.419917,12.916598,6.077593,2.968880,18.229461
std,6.210391,4.210854,983.514693,11.210459,981.20363,11.075136,NaN,0.254552,5.012922,7.688404,3.168053,6.241687,5.892951,7.514385,4.379388,5.233218,4.753647,4.108262,3.294258,2.62981,4.003236,4.401351,7.626153,2.832170,6.415524,5.104592,6.645874,4.500808,4.564933,3.756773,4.434863,2.875043,2.051907,4.231477
min,2003.000000,134.000000,1101.000000,47.000000,1101.00000,21.000000,NaN,0.000000,13.000000,34.000000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,3.000000,2.000000,0.000000,0.00000,3.000000,7.000000,37.000000,0.000000,3.000000,0.000000,0.000000,0.000000,8.000000,2.000000,2.000000,0.000000,0.000000,3.000000
25%,2011.000000,137.000000,1257.000000,68.000000,1267.25000,55.000000,NaN,0.000000,24.000000,53.000000,4.000000,14.000000,11.000000,15.000000,8.000000,23.000000,12.000000,9.000000,5.000000,2.00000,13.000000,20.000000,54.000000,4.000000,16.000000,7.000000,10.000000,7.000000,18.000000,9.000000,10.000000,4.000000,1.000000,15.000000
50%,2015.000000,138.000000,1411.500000,75.000000,1417.00000,62.000000,NaN,0.000000,27.000000,57.000000,6.500000,18.000000,14.000000,20.000000,11.000000,26.000000,15.000000,12.000000,6.000000,4.00000,15.000000,23.000000,59.000000,6.000000,20.000000,10.000000,15.000000,10.000000,21.000000,11.000000,12.000000,6.000000,3.000000,18.000000
75%,2021.000000,141.000000,3257.000000,83.000000,3245.75000,69.000000,NaN,0.000000,30.000000,63.000000,9.000000,22.000000,19.000000,25.000000,14.000000,30.000000,18.000000,14.000000,9.000000,6.00000,18.000000,26.000000,64.000000,8.000000,24.000000,14.000000,20.000000,14.000000,24.000000,14.000000,16.000000,8.000000,4.000000,21.000000
max,2025.000000,155.000000,3462.000000,140.000000,3471.00000,108.000000,NaN,2.000000,59.000000,91.000000,25.000000,51.000000,38.000000,48.000000,27.000000,54.000000,38.000000,34.000000,24.000000,16.00000,31.000000,40.000000,88.000000,18.000000,57.000000,31.000000,45.000000,29.000000,42.000000,29.000000,32.000000,22.000000,13.000000,33.000000

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT
count,4302.000000,4302.000000,4302.000000,4302.000000,4302.000000,4302.000000,4302,4302.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,3471,NaN
mean,2007.459554,139.745467,2083.172245,76.512552,2088.045793,62.732682,NaN,0.049512
std,10.916611,4.214000,985.909561,11.627170,983.247261,11.418021,NaN,0.240347
min,1985.000000,134.000000,1101.000000,43.000000,1101.000000,21.000000,NaN,0.000000
25%,2000.000000,137.000000,1246.000000,69.000000,1266.000000,55.000000,NaN,0.000000
50%,2008.000000,138.000000,1401.000000,76.000000,1412.000000,63.000000,NaN,0.000000
75%,2016.000000,141.000000,3257.000000,84.000000,3250.000000,70.000000,NaN,0.000000
max,2025.000000,155.000000,3464.000000,149.000000,3471.000000,115.000000,NaN,3.000000

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,WFGM3,WFGA3,WFTM,WFTA,WOR,WDR,WAst,WTO,WStl,WBlk,WPF,LFGM,LFGA,LFGM3,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
count,211716.000000,211716.000000,211716.00000,211716.000000,211716.000000,211716.000000,211716,211716.000000,211716.000000,211716.000000,211716.000000,211716.000000,211716.000000,211716.000000,211716.000000,211716.000000,211716.000000,211716.000000,211716.000000,211716.000000,211716.000000,211716.000000,211716.000000,211716.000000,211716.000000,211716.000000,211716.000000,211716.00000,211716.000000,211716.000000,211716.000000,211716.000000,211716.000000,211716.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,121160,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,2016.123699,70.200037,2110.92053,74.347182,2108.627468,61.307204,NaN,0.061630,26.237209,57.166081,6.963810,18.940973,14.908954,20.851622,10.973960,25.962469,14.838156,13.492216,7.672505,3.732968,16.683028,22.055338,57.335029,5.734385,19.376311,11.462143,16.826839,10.68812,21.860960,11.232481,15.130113,6.462365,2.850262,18.797054
std,6.352989,36.204111,988.40631,11.458923,991.724800,11.413701,NaN,0.286696,4.821583,7.811166,3.183975,6.366821,6.112946,7.971070,4.461546,5.090498,4.530240,4.464958,3.495792,2.417302,4.214254,4.498934,7.725899,2.822170,6.359618,5.248387,6.986135,4.40488,4.704645,3.770125,5.044259,2.985238,2.033009,4.585103
min,2003.000000,0.000000,1101.00000,30.000000,1101.000000,11.000000,NaN,0.000000,9.000000,26.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,1.000000,0.000000,0.000000,0.000000,1.000000,3.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.000000,0.000000,0.000000,3.000000
25%,2011.000000,37.000000,1262.00000,66.000000,1255.000000,54.000000,NaN,0.000000,23.000000,52.000000,5.000000,14.000000,11.000000,15.000000,8.000000,22.000000,12.000000,10.000000,5.000000,2.000000,14.000000,19.000000,52.000000,4.000000,15.000000,8.000000,12.000000,8.00000,19.000000,9.000000,12.000000,4.000000,1.000000,16.000000
50%,2016.000000,73.000000,1416.00000,74.000000,1410.000000,61.000000,NaN,0.000000,26.000000,57.000000,7.000000,19.000000,14.000000,20.000000,11.000000,26.000000,15.000000,13.000000,7.000000,3.000000,16.000000,22.000000,57.000000,5.000000,19.000000,11.000000,16.000000,10.00000,22.000000,11.000000,15.000000,6.000000,3.000000,19.000000
75%,2022.000000,101.000000,3247.00000,82.000000,3248.000000,69.000000,NaN,0.000000,29.000000,62.000000,9.000000,23.000000,19.000000,26.000000,14.000000,29.000000,18.000000,16.000000,10.000000,5.000000,19.000000,25.000000,62.000000,8.000000,23.000000,15.000000,21.000000,13.00000,25.000000,14.000000,18.000000,8.000000,4.000000,22.000000
max,2026.000000,132.000000,3481.00000,149.000000,3481.000000,144.000000,NaN,6.000000,58.000000,113.000000,30.000000,63.000000,50.000000,67.000000,45.000000,58.000000,45.000000,40.000000,36.000000,21.000000,42.000000,53.000000,111.000000,25.000000,80.000000,48.000000,65.000000,38.00000,53.000000,34.000000,49.000000,26.000000,18.000000,47.000000

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT
count,341084.000000,341084.000000,341084.000000,341084.000000,341084.000000,341084.000000,341084,341084.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,H,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,197698,NaN
mean,2009.264041,72.538340,2122.367789,74.886207,2120.103112,61.813858,NaN,0.045693
std,10.918413,34.914787,990.692632,11.903665,993.102146,11.613441,NaN,0.247946
min,1985.000000,0.000000,1101.000000,30.000000,1101.000000,11.000000,NaN,0.000000
25%,2001.000000,42.000000,1264.000000,67.000000,1257.000000,54.000000,NaN,0.000000
50%,2010.000000,75.000000,1418.000000,74.000000,1414.000000,61.000000,NaN,0.000000
75%,2018.000000,103.000000,3250.000000,82.000000,3250.000000,69.000000,NaN,0.000000
max,2026.000000,132.000000,3481.000000,186.000000,3481.000000,150.000000,NaN,6.000000

              Season        TeamID ConfAbbrev
count   23606.000000  23606.000000      23606
unique           NaN           NaN         51
top              NaN           NaN      a_ten
freq             NaN           NaN        915
mean     2008.920910   2120.280437        NaN
std        11.039912    991.923645        NaN
min      1985.000000   1101.000000        NaN
25%      2001.000000   1259.000000        NaN
50%      2010.000000   1416.000000        NaN
75%      2018.000000   3249.000000        NaN
max      2026.000000   3481.000000        NaN

              Rank Conference       season conf  M_W
count   320.000000        320   320.000000  320  320
unique         NaN         33          NaN   33    2
top            NaN        SEC          NaN  sec    M
freq           NaN         10          NaN   10  160
mean     16.512500        NaN  2023.975000  NaN  NaN
std       9.269215        NaN     1.407325  NaN  NaN
min       1.000000        NaN  2022.000000  NaN  NaN
25%       8.750000        NaN  2023.000000  NaN  NaN
50%      16.500000        NaN  2024.000000  NaN  NaN
75%      24.250000        NaN  2025.000000  NaN  NaN
max      33.000000        NaN  2026.000000  NaN  NaN

In [9]:
# Some results above were 'interesting'; check dtypes
display(TourneySeeds.dtypes)
display(SampleSubmission.dtypes)
display(Seasons.dtypes)
display(Teams.dtypes)
display(TourneySlots.dtypes)
display(TourneyDetailedResults.dtypes)
display(TourneyCompactResults.dtypes)
display(RegularDetailedResults.dtypes)
display(RegularCompactResults.dtypes)
display(TeamConf.dtypes)
display(ConfRank.dtypes)

Season     int64
Seed      object
TeamID     int64
dtype: object

ID       object
Pred    float64
dtype: object

Season      int64
DayZero    object
RegionW    object
RegionX    object
RegionY    object
RegionZ    object
dtype: object

TeamID             int64
TeamName          object
FirstD1Season    float64
LastD1Season     float64
dtype: object

Season         int64
Slot          object
StrongSeed    object
WeakSeed      object
dtype: object

Season      int64
DayNum      int64
WTeamID     int64
WScore      int64
LTeamID     int64
LScore      int64
WLoc       object
NumOT       int64
WFGM        int64
WFGA        int64
WFGM3       int64
WFGA3       int64
WFTM        int64
WFTA        int64
WOR         int64
WDR         int64
WAst        int64
WTO         int64
WStl        int64
WBlk        int64
WPF         int64
LFGM        int64
LFGA        int64
LFGM3       int64
LFGA3       int64
LFTM        int64
LFTA        int64
LOR         int64
LDR         int64
LAst        int64
LTO         int64
LStl        int64
LBlk        int64
LPF         int64
dtype: object

Season      int64
DayNum      int64
WTeamID     int64
WScore      int64
LTeamID     int64
LScore      int64
WLoc       object
NumOT       int64
dtype: object

Season      int64
DayNum      int64
WTeamID     int64
WScore      int64
LTeamID     int64
LScore      int64
WLoc       object
NumOT       int64
WFGM        int64
WFGA        int64
WFGM3       int64
WFGA3       int64
WFTM        int64
WFTA        int64
WOR         int64
WDR         int64
WAst        int64
WTO         int64
WStl        int64
WBlk        int64
WPF         int64
LFGM        int64
LFGA        int64
LFGM3       int64
LFGA3       int64
LFTM        int64
LFTA        int64
LOR         int64
LDR         int64
LAst        int64
LTO         int64
LStl        int64
LBlk        int64
LPF         int64
dtype: object

Season      int64
DayNum      int64
WTeamID     int64
WScore      int64
LTeamID     int64
LScore      int64
WLoc       object
NumOT       int64
dtype: object

Season         int64
TeamID         int64
ConfAbbrev    object
dtype: object

Rank           int64
Conference    object
season         int64
conf          object
M_W           object
dtype: object

### Create Variables of Interest

In [10]:
### Calculate Winning Percentage for each team in the postseason by season

# Select relevant columns, rename for merge;
# Add variable for outcome of game (team1win): Winning team gets a 1, Losing team gets a 0
set1 = TourneyCompactResults[['Season', 'WTeamID']].rename(columns = {'Season':'season', 'WTeamID':'team'}).assign(team1win = 1)
set2 = TourneyCompactResults[['Season', 'LTeamID']].rename(columns = {'Season':'season', 'LTeamID':'team'}).assign(team1win = 0)

# Merge together
full_set = pd.concat([set1,set2])
display(full_set.head(), full_set.shape)

   season  team  team1win
0    1985  1116         1
1    1985  1120         1
2    1985  1207         1
3    1985  1229         1
4    1985  1242         1

(8604, 3)

In [11]:
# Get mean of wins for each team by season
winperc_noseed = full_set.groupby(['season', 'team']).mean().rename(
    columns={'team1win':'winpercintourney'}).dropna().reset_index()

# sort dataset in descending order of winpercintourney (winner of tournament at top)
winperc_noseed = winperc_noseed.sort_values(by=['season', 'winpercintourney'], ascending=False).reset_index(drop=True)

# create pseudo-dummy for later manipulation. 1 means that team was in the tourney that season
winperc_noseed['intourney'] = 1
display(winperc_noseed.head(), winperc_noseed.shape)

   season  team  winpercintourney  intourney
0    2025  1196          1.000000          1
1    2025  3163          1.000000          1
2    2025  1222          0.833333          1
3    2025  3376          0.833333          1
4    2025  1120          0.800000          1

(4369, 4)

##### This is the win percentage; team1win ranges between [0,1], where 
> ##### 1 = team won every game in that tourney (and the championship)
> ##### 0 = they lost in the first round (eliminated)
> ##### Each subsequent win% level is a different round of the tourney

In [76]:
### Merge with tournament seed data

seeds = TourneySeeds.rename(columns = {'Season':'season', 'Seed':'seed', 'TeamID':'team'})
seeds['seed_num'] = seeds['seed'].str[1:3].astype(int)
seeds = seeds.drop('seed', axis = 1)

winperc = winperc_noseed.merge(seeds, how='outer', on=['season', 'team'])
display(winperc.head(), winperc.shape)

   season  team  winpercintourney  intourney  seed_num
0    1985  1104          0.666667        1.0         7
1    1985  1112          0.000000        1.0        10
2    1985  1116          0.500000        1.0         9
3    1985  1120          0.666667        1.0        11
4    1985  1130          0.666667        1.0        11

(4506, 5)

In [81]:
winperc.describe

<bound method NDFrame.describe of       season  team  winpercintourney  intourney  seed_num
0       1985  1104          0.666667        1.0         7
1       1985  1112          0.000000        1.0        10
2       1985  1116          0.500000        1.0         9
3       1985  1120          0.666667        1.0        11
4       1985  1130          0.666667        1.0        11
...      ...   ...               ...        ...       ...
4501    2026  3449               NaN        NaN         6
4502    2026  3452               NaN        NaN         4
4503    2026  3453               NaN        NaN        13
4504    2026  3465               NaN        NaN        16
4505    2026  3471               NaN        NaN        14

[4506 rows x 5 columns]>

In [82]:
# Merging Team data with Conference data
Teams = Teams.rename(columns = {'TeamID':'Team_Id', 'TeamName':'TeamName', 'FirstD1Season':'FirstD1Season', 'LastD1Season':'LastD1Season'})
TeamConf = TeamConf.rename(columns = {'Season':'season', 'TeamID':'Team_Id', 'ConfAbbrev':'Conf_ID'})
Team_with_Conf = TeamConf.merge(Teams, how='right', on='Team_Id')[[
    'season', 'Team_Id', 'Conf_ID']].rename(columns={'season':'season', 'Team_Id':'team', 'Conf_ID':'conf'})
Team_with_Conf.head()

   season  team       conf
0  2014.0  1101  southland
1  2015.0  1101  southland
2  2016.0  1101  southland
3  2017.0  1101  southland
4  2018.0  1101  southland

### Calculating Z-scores

##### Box Score metrics are standardized here as z-scores, allowing for direct comparison of predictor importance
##### This is largely done to put variables on the same scale, making relative importance clear
> ##### Shots Attempted is likely to be on a larger scale than Steals or Blocks
> ##### EFG is a percentage, while other measures are integers

In [83]:
### Offensive Efficiency

# Winning/Losing Teams' Effective Field Goal Percentage (efg)
RegularDetailedResults['WEFG'] = (RegularDetailedResults['WFGM'] + 
    (1.5*RegularDetailedResults['WFGM3']))/(RegularDetailedResults['WFGA'] + 
                                         RegularDetailedResults['WFGA3'])
RegularDetailedResults['LEFG'] = (RegularDetailedResults['LFGM'] + 
    (1.5*RegularDetailedResults['LFGM3']))/(RegularDetailedResults['LFGA'] + 
                                         RegularDetailedResults['LFGA3'])
# Winning/Losing Teams' Shots Attempted (sa)
# sa = fga + fga3
RegularDetailedResults['WSA'] = (RegularDetailedResults['WFGA'] + 
                                 (RegularDetailedResults['WFGA3']))
RegularDetailedResults['LSA'] = (RegularDetailedResults['LFGA'] + 
                                 (RegularDetailedResults['LFGA3']))

display(RegularDetailedResults.head())

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,WFGM3,WFGA3,WFTM,WFTA,WOR,WDR,WAst,WTO,WStl,WBlk,WPF,LFGM,LFGA,LFGM3,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF,WEFG,LEFG,WSA,LSA
0,2003,10,1104,68,1328,62,N,0,27,58,3,14,11,18,14,24,13,23,7,1,22,22,53,2,10,16,22,10,22,8,18,9,2,20,0.437500,0.396825,72,63
1,2003,10,1272,70,1393,63,N,0,26,62,8,20,10,19,15,28,16,13,4,4,18,24,67,6,24,9,20,20,25,7,12,8,6,16,0.463415,0.362637,82,91
2,2003,11,1266,73,1437,61,N,0,24,58,8,18,17,29,17,26,15,10,5,2,25,22,73,3,26,14,23,31,22,9,12,2,5,23,0.473684,0.267677,76,99
3,2003,11,1296,56,1457,50,N,0,18,38,3,9,17,31,6,19,11,12,14,2,18,18,49,6,22,8,15,17,20,9,19,4,3,23,0.478723,0.380282,47,71
4,2003,11,1400,77,1208,71,N,0,30,61,6,14,11,13,17,22,12,14,4,4,20,24,62,6,16,17,27,21,15,12,10,7,1,14,0.520000,0.423077,75,78

##### Effective Field Goal Perfentage (eFG%) adjusts traditional field goal percentage to account for the higher value of 3-point shots
##### efg = (field goals made + (0.5 * 3pt shots made)) / (field goals attempted + 3pt shots attemtped)

In [84]:
# Select relevant columns and rename for winning/losing teams; merge
e1 = RegularDetailedResults[['Season', 'WTeamID', 'WEFG', 'WSA']].rename(
    columns = {'Season':'season', 'WTeamID':'team', 'WEFG':'EFG', 'WSA':'shot_attempts'})
e2 = RegularDetailedResults[['Season', 'LTeamID', 'LEFG', 'LSA']].rename(
    columns = {'Season':'season', 'LTeamID':'team', 'LEFG':'EFG', 'LSA':'shot_attempts'})
e3 = pd.concat([e1,e2])

# Add conference column to e3
# Rename TeamConf df columns for merge w/ Teams df, merge w/ e3
TeamConf = TeamConf.rename(columns = {'season':'season', 'team_id':'Team_Id', 'conference':'Conf_ID'})
Team_with_Conf = TeamConf.merge(Teams, how='right', on='Team_Id')[[
    'season', 'Team_Id', 'Conf_ID']].rename(columns={'season':'season', 'Team_Id':'team', 'Conf_ID':'conf'})
# Merge Conf df with main df
e4 = e3.merge(Team_with_Conf, how='left', on = ['team', 'season'])

# Get mean and std dev of efficiency variables for each team
# This is the mean/std for each team by season and conference
e5 = e4.groupby(['season', 'team', 'conf']).mean().dropna().reset_index()
e5.columns = ['season', 'team', 'conf', 'efg_mean', 'sa_mean']

# Get season league-wide efficiency mean/std for z-score
e6 = e5.groupby('season').agg({'efg_mean':['mean', 'std'], 'sa_mean':['mean', 'std']}).dropna().reset_index()
e6.columns = ['_'.join(col).strip() for col in e6.columns.values] 
e6.columns = ['season', 'league_efg_mean', 'league_efg_std', 'league_sa_mean', 'league_sa_std']

# Merge with team-level df
e7 = e6.merge(e5, how='right', on='season')

# calculate z-scores for efg
e7['z.efg'] = (e7['efg_mean'] - e7['league_efg_mean']) / e7['league_efg_std']
# calculate zscore for sa (to interact the efficient field goal with number of shot attempts) 
# 1 for 1 shouldn't be the same as 10 for 10
e7['z.sa'] = (e7['sa_mean'] - e7['league_sa_mean']) / e7['league_sa_std']

# select meaningful variables
e7 = e7[['team', 'season', 'conf', 'z.efg', 'z.sa']]
display(e7.head(), e7.shape)

   team  season  conf     z.efg      z.sa
0  1102    2003   mwc  1.939737 -2.396712
1  1103    2003   mac  1.206692 -0.392774
2  1104    2003   sec -0.867425  0.511890
3  1105    2003  swac -1.037090  1.458888
4  1106    2003  swac -0.369902 -0.215260

(14311, 5)

In [85]:
### Z-score of average point differential of each team by conference by year over the regular season

# Create point difference variables for each team in each matchup
RegularDetailedResults['Wptdiff'] = RegularDetailedResults['WScore'] - RegularDetailedResults['LScore']
RegularDetailedResults['Lptdiff'] = RegularDetailedResults['LScore'] - RegularDetailedResults['WScore']

# Select relevant columns and rename for winning/losing teams; merge
p1 = RegularDetailedResults[['Season', 'WTeamID', 'Wptdiff']].rename(
    columns = {'Season':'season', 'WTeamID':'team', 'Wptdiff':'ptdiff'})
p2 = RegularDetailedResults[['Season', 'LTeamID', 'Lptdiff']].rename(
    columns = {'Season':'season', 'LTeamID':'team', 'Lptdiff':'ptdiff'})
p3 = pd.concat([p1,p2])

# Add conference column to p3
p4 = p3.merge(Team_with_Conf, how='left', on = ['team', 'season'])

# Get mean and std dev of efficiency variables for each team
# This is the mean/std for each team by season and conference
p5 = p4.groupby(['season', 'team', 'conf']).mean().dropna().reset_index()
p5.columns = ['season', 'team', 'conf', 'ptdiff_mean']

# calculate league mean and sd
# add conf
p6 = p5.groupby('season').agg({'ptdiff_mean':['mean', 'std']}).dropna().reset_index()
p6.columns = ['_'.join(col).strip() for col in p6.columns.values] 
p6.columns = ['season', 'league_ptdiff_mean', 'league_ptdiff_std']

# Merge with team-level df
p7 = p6.merge(p5, how='right', on='season')

# calculate z-scores for pt diff
p7['z.pt'] = (p7['ptdiff_mean'] - p7['league_ptdiff_mean']) / p7['league_ptdiff_std']

# select meaningful variables
p7 = p7[['team', 'season', 'conf', 'z.pt']]
display(p7.head(), p7.shape)

   team  season  conf      z.pt
0  1102    2003   mwc  0.067261
1  1103    2003   mac  0.125825
2  1104    2003   sec  0.689834
3  1105    2003  swac -0.724836
4  1106    2003  swac  0.006656

(14311, 4)

In [86]:
### Caculate momentum heading into the post-season

# Calculate W-L record at day 100 for each team by season

# Identify teams in each matchup in every season
m1 = SampleSubmission['ID'].str.split('_', expand=True).iloc[:, ::-1]  # reverse the 3 columns
m1.columns = ['season', 'team1', 'team2']

# Combine with df for game-level stats
m2 = RegularCompactResults.merge(full_set, how='left', left_on=['Season', 'WTeamID'], right_on=['season', 'team']).drop(
    ['season', 'team'], axis=1)
m3= m2.merge(full_set, how='left', left_on=['Season', 'LTeamID'], right_on=['season', 'team']).drop(['season', 'team'], axis=1)

#
m4 = m3[['Season', 'WTeamID', 'DayNum']].rename(columns={'Season':'season', 'WTeamID':'team', 'DayNum':'day'}).assign(team1win = 1)
m5 = m3[['Season', 'LTeamID', 'DayNum']].rename(columns={'Season':'season', 'LTeamID':'team', 'DayNum':'day'}).assign(team1win = 0)
m6 = pd.concat([m5,m4])

#
m7 = m6.merge(Team_with_Conf, how='left', on=['team', 'season'])

#
m8 = m7[m7['day'] <= 100].groupby(['team', 'season', 'conf']).mean().dropna().reset_index().rename(
    columns = {'team1win':'winsbefore'}).sort_values(['season', 'winsbefore'], ascending=[True, False])

#
m8['rank'] = m8.groupby(['season','conf']).winsbefore.rank(method='dense', ascending=False).astype(int)
        
# Create categorical rankings based on ranking in conference
m8['top'] = (m8['rank'] <= 3).astype(int)
m8['mid'] = ((m8['rank'] >= 4) & (m8['rank'] <= 7)).astype(int)
m8['bot'] = (m8['rank'] >= 8).astype(int)    

# Calculate W-L record after day 100 for each team by season
m9 = m7[m7['day'] >= 101].groupby(['team', 'season', 'conf']).mean().dropna().reset_index().rename(
    columns = {'team1win':'winsafter'}).sort_values(['season', 'winsafter'], ascending=[True, False])

# Add winsafter to rankings df
m10 = m8.merge(m9, how='left', on=['team', 'season', 'conf']).drop(['day_x', 'day_y'], axis = 1)

# Normalize winsbefore and winsafter by season
m10['z.winsbefore'] = m10.groupby('season')['winsbefore'].transform(
    lambda x: (x - x.mean()) / x.std()
)

m10['z.winsafter'] = m10.groupby('season')['winsafter'].transform(
    lambda x: (x - x.mean()) / x.std()
)

m10 = m10.drop(['winsbefore','winsafter'], axis=1)

display(m10.head(), m10.shape)

   team  season      conf  rank  top  mid  bot  z.winsbefore  z.winsafter
0  1385    1985  big_east     1    1    0    0      2.722163     0.822607
1  1272    1985     metro     1    1    0    0      2.567872     1.408784
2  1374    1985       swc     1    1    0    0      2.357865    -0.705003
3  1293    1985       ovc     1    1    0    0      2.267862    -1.308942
4  1298    1985     ecacs     1    1    0    0      2.017854     1.469178

(23604, 9)

##### Momentum is a created variable that looks at how many wins a team has going in to the postseason
> ##### This is calculated by the number of games won after day 100 of the season
##### In addition, teams are ranked at the day 100 mark to further look at whether momentum heading into the post season matters more for teams that were better-/worse- performing prior to that point
> ##### 'Top' = ranked 3rd or better within their conference
> ##### 'Mid' = ranked between 4th and 7th within their conference
> ##### 'Bot' = ranked 8th or worse within their conference

##### How much momentum a team has going in to the post season is a popular talking point among pundits leading up to March Madness
##### Winning late-season games may also be particularly important for 'bubble teams', or teams that don't automatically qualify for March Madness by winning their conference tournament, but still have a chance to make it via the selection committee

In [87]:
### Clutch - how many close games (pt. diff <= 5 points)

# Start from p4 - already has ptdiff calculated
c1 = p4.copy()

# Create necessary variables for Clutch calculations
c1['close'] = c1['ptdiff'].between(-5, 5)
c1['team1win'] = c1['ptdiff'] > 0

clutch = (
    c1[c1['close']]
    .groupby(['team','season','conf'])['team1win']
    .mean()
    .rename('clutch_mean')
)

close_rate = (
    c1.groupby(['team','season','conf'])['close']
    .mean()
    .rename('close_mean')
)

c2 = pd.concat([clutch, close_rate], axis=1).reset_index()

# Normalize clutch_mean and close_mean by season
c2['z.clutch'] = c2.groupby('season')['clutch_mean'].transform(
    lambda x: (x - x.mean()) / x.std()
)

c2['z.close'] = c2.groupby('season')['close_mean'].transform(
    lambda x: (x - x.mean()) / x.std()
)

c2 = c2.drop(['clutch_mean','close_mean'], axis=1)

display(c2.head(), c2.shape)

   team  season       conf  z.clutch   z.close
0  1101    2014  southland -1.162676 -0.661234
1  1101    2015  southland -2.329929 -1.882109
2  1101    2016  southland -0.585774  0.592304
3  1101    2017  southland  0.213987  2.103544
4  1101    2018  southland  0.419166  2.163727

(14311, 5)

##### Clutch is a metric created to calculate the number of close games a team has won
> ##### 'close' games are defined as a game that had a final score within 5 points
> ##### clutch wins are the number of close wins / number of close games (% of close games won)

##### Also calculated is the percentage of close games a team had, close_z
> ##### Defined as number of close games / total games, standardized

##### Teams that were able to win more close games may do better under pressure or may be more reliable in tough situations. There are different scenarios where this may occur: games that are close throughout the contest, where a team overcomes a large deficit, or where a team holds off a resurging opponent are just a few. These teams may perform better in high-stakes situations like March Madness

In [88]:
### Grit - how many games with overtime won 

# Start from m3 - has necessary variables for calculations (OT)
g1 = m3[['Season', 'WTeamID', 'DayNum', 'NumOT']].assign(team1win = 1).rename(
    columns={'Season':'season', 'WTeamID':'team', 'DayNum':'day', 'NumOT':'ot'})
g2 = m3[['Season', 'LTeamID', 'DayNum', 'NumOT']].assign(team1win = 0).rename(
    columns={'Season':'season', 'LTeamID':'team', 'DayNum':'day', 'NumOT':'ot'})
g3 = pd.concat([g1,g2])

# Add conference data
g4 = g3.merge(Team_with_Conf, how='left', on=['team', 'season'])

# Create dummy, where =1 if game had an OT
g4['has_ot'] = (g4['ot'] > 0)

# Calculate Grit

grit = (
    g4[g4['has_ot']]  # only OT games
    .groupby(['team', 'season', 'conf'])['team1win']
    .mean()
    .rename('grit_mean')
)

ot_freq = (
    g4.groupby(['team', 'season', 'conf'])['has_ot']
    .mean()
    .rename('has_ot_mean')
)

#
g5 = pd.concat([grit, ot_freq], axis=1).reset_index()

# Add z-scores for grit_mean and has_ot_mean by season
g5['z.grit'] = g5.groupby('season')['grit_mean'].transform(
    lambda x: (x - x.mean()) / x.std()
)

g5['z.has_ot'] = g5.groupby('season')['has_ot_mean'].transform(
    lambda x: (x - x.mean()) / x.std()
)

g5 = g5.drop(['grit_mean','has_ot_mean'],axis=1)

display(g5.head(), g5.shape)

   team  season       conf    z.grit  z.has_ot
0  1101    2014  southland -1.243557  0.843151
1  1101    2016  southland -1.212715 -0.351353
2  1101    2017  southland  0.388897  1.574663
3  1101    2018  southland  1.284799 -0.450775
4  1101    2020  southland  0.003512  2.265943

(23604, 5)

##### Grit is the last created metric, measuring the number of overtime games that a team has won
> ##### Grit_z is a team's proportion of OT wins in that season, standardized
> ##### Similarly, has_ot_z is the proportion of OT games that team had each year, standardized

In [89]:
### Z-score of point totals of each team within each season across all teams

o1 = RegularCompactResults[['Season', 'WTeamID', 'WScore']].rename(
    columns={'Season':'season', 'WTeamID':'team', 'WScore':'score'})
o2 = RegularCompactResults[['Season', 'LTeamID', 'LScore']].rename(
    columns={'Season':'season', 'LTeamID':'team', 'LScore':'score'})
o3 = pd.concat([o1,o2])

# calculate team mean by conference and season
o4 = o3.merge(Team_with_Conf, how='left', on=['team', 'season'])
o5 = o4.groupby(['team', 'season', 'conf']).mean().rename(
    columns={'score':'score_mean'}).dropna().reset_index()

# calculate league mean and sd
# add conf
o6 = o5.groupby('season').agg({'score_mean':['mean', 'std']}).dropna().reset_index()
o6.columns = ['_'.join(col).strip() for col in o6.columns.values] 
o6.columns = ['season', 'league_score_mean', 'league_score_std']

# Merge with team-level df
o7 = o6.merge(o5, how='right', on='season')

# calculate z-scores for efg
o7['z.off'] = (o7['score_mean'] - o7['league_score_mean']) / o7['league_score_std']

# select meaningful variables
o7 = o7[['team', 'season', 'conf', 'z.off']]
display(o7.head(), o7.shape)

   team  season       conf     z.off
0  1101    2014  southland -0.889271
1  1101    2015  southland -0.736346
2  1101    2016  southland  0.225362
3  1101    2017  southland -0.097933
4  1101    2018  southland  0.216324

(23604, 4)

In [90]:
### Z-score of points allowed of each team within each season across all teams

d1 = RegularCompactResults[['Season', 'WTeamID', 'LScore']].rename(
    columns={'Season':'season', 'WTeamID':'team', 'LScore':'score'})
d2 = RegularCompactResults[['Season', 'LTeamID', 'WScore']].rename(
    columns={'Season':'season', 'LTeamID':'team', 'WScore':'score'})
d3 = pd.concat([d1,d2])

# calculate team mean by conference and season
d4 = d3.merge(Team_with_Conf, how='left', on=['team', 'season'])
d5 = d4.groupby(['team', 'season', 'conf']).mean().rename(
    columns={'score':'score_mean'}).dropna().reset_index()

# calculate league mean and sd
# add conf
d6 = d5.groupby('season').agg({'score_mean':['mean', 'std']}).dropna().reset_index()
d6.columns = ['_'.join(col).strip() for col in d6.columns.values] 
d6.columns = ['season', 'league_score_mean', 'league_score_std']

# Merge with team-level df
d7 = d6.merge(d5, how='right', on='season')

# calculate z-scores for efg
d7['z.def'] = (d7['score_mean'] - d7['league_score_mean']) / d7['league_score_std']

# select meaningful variables
d7 = d7[['team', 'season', 'conf', 'z.def']]
display(d7.head(), d7.shape)

   team  season       conf     z.def
0  1101    2014  southland  1.657657
1  1101    2015  southland  1.111848
2  1101    2016  southland  1.109909
3  1101    2017  southland  0.552080
4  1101    2018  southland  0.522332

(23604, 4)

In [91]:
### Z-score of assists of each team within each season across all teams

a1 = RegularDetailedResults[['Season', 'WTeamID', 'WAst']].rename(
    columns={'Season':'season', 'WTeamID':'team', 'WAst':'assists'})
a2 = RegularDetailedResults[['Season', 'LTeamID', 'LAst']].rename(
    columns={'Season':'season', 'LTeamID':'team', 'LAst':'assists'})
a3 = pd.concat([a1,a2])

# calculate team mean by conference and season
a4 = a3.merge(Team_with_Conf, how='left', on=['team', 'season'])
a5 = a4.groupby(['team', 'season', 'conf']).mean().rename(
    columns={'assists':'assists_mean'}).dropna().reset_index()

# calculate league mean and sd
# add conf
a6 = a5.groupby('season').agg({'assists_mean':['mean', 'std']}).dropna().reset_index()
a6.columns = ['_'.join(col).strip() for col in a6.columns.values] 
a6.columns = ['season', 'league_assists_mean', 'league_assists_std']

# Merge with team-level df
a7 = a6.merge(a5, how='right', on='season')

# calculate z-scores for efg
a7['z.Ast'] = (a7['assists_mean'] - a7['league_assists_mean']) / a7['league_assists_std']

# select meaningful variables
a7 = a7[['team', 'season', 'conf', 'z.Ast']]
display(a7.head(), a7.shape)

   team  season       conf     z.Ast
0  1101    2014  southland -1.396338
1  1101    2015  southland -0.365026
2  1101    2016  southland -0.070147
3  1101    2017  southland  0.185252
4  1101    2018  southland  0.265688

(14311, 4)

In [92]:
### Z-score of turnovers of each team within each season across all teams

t1 = RegularDetailedResults[['Season', 'WTeamID', 'WTO']].rename(
    columns={'Season':'season', 'WTeamID':'team', 'WTO':'turnovers'})
t2 = RegularDetailedResults[['Season', 'LTeamID', 'LTO']].rename(
    columns={'Season':'season', 'LTeamID':'team', 'LTO':'turnovers'})
t3 = pd.concat([t1,t2])

# calculate team mean by conference and season
t4 = t3.merge(Team_with_Conf, how='left', on=['team', 'season'])
t5 = t4.groupby(['team', 'season', 'conf']).mean().rename(
    columns={'turnovers':'turnovers_mean'}).dropna().reset_index()

# calculate league mean and sd
# add conf
t6 = t5.groupby('season').agg({'turnovers_mean':['mean', 'std']}).dropna().reset_index()
t6.columns = ['_'.join(col).strip() for col in t6.columns.values] 
t6.columns = ['season', 'league_turnovers_mean', 'league_turnovers_std']

# Merge with team-level df
t7 = t6.merge(t5, how='right', on='season')

# calculate z-scores for efg
t7['z.TO'] = (t7['turnovers_mean'] - t7['league_turnovers_mean']) / t7['league_turnovers_std']

# select meaningful variables
t7 = t7[['team', 'season', 'conf', 'z.TO']]
display(t7.head(), t7.shape)

   team  season       conf      z.TO
0  1101    2014  southland  0.328513
1  1101    2015  southland -0.596794
2  1101    2016  southland -0.394400
3  1101    2017  southland  0.015676
4  1101    2018  southland  0.018200

(14311, 4)

In [93]:
### Z-score of steals of each team within each season across all teams

s1 = RegularDetailedResults[['Season', 'WTeamID', 'WStl']].rename(
    columns={'Season':'season', 'WTeamID':'team', 'WStl':'steals'})
s2 = RegularDetailedResults[['Season', 'LTeamID', 'LStl']].rename(
    columns={'Season':'season', 'LTeamID':'team', 'LStl':'steals'})
s3 = pd.concat([s1,s2])

# calculate team mean by conference and season
s4 = s3.merge(Team_with_Conf, how='left', on=['team', 'season'])
s5 = s4.groupby(['team', 'season', 'conf']).mean().rename(
    columns={'steals':'steals_mean'}).dropna().reset_index()

# calculate league mean and sd
# add conf
s6 = s5.groupby('season').agg({'steals_mean':['mean', 'std']}).dropna().reset_index()
s6.columns = ['_'.join(col).strip() for col in s6.columns.values] 
s6.columns = ['season', 'league_steals_mean', 'league_steals_std']

# Merge with team-level df
s7 = s6.merge(s5, how='right', on='season')

# calculate z-scores for efg
s7['z.Stl'] = (s7['steals_mean'] - s7['league_steals_mean']) / s7['league_steals_std']

# select meaningful variables
s7 = s7[['team', 'season', 'conf', 'z.Stl']]
display(s7.head(), s7.shape)

   team  season       conf     z.Stl
0  1101    2014  southland -0.642247
1  1101    2015  southland -0.598763
2  1101    2016  southland -0.075650
3  1101    2017  southland  0.072088
4  1101    2018  southland  0.172107

(14311, 4)

In [94]:
### Z-score of blocks of each team within each season across all teams

b1 = RegularDetailedResults[['Season', 'WTeamID', 'WBlk']].rename(
    columns={'Season':'season', 'WTeamID':'team', 'WBlk':'blocks'})
b2 = RegularDetailedResults[['Season', 'LTeamID', 'LBlk']].rename(
    columns={'Season':'season', 'LTeamID':'team', 'LBlk':'blocks'})
b3 = pd.concat([b1,b2])

# calculate team mean by conference and season
b4 = b3.merge(Team_with_Conf, how='left', on=['team', 'season'])
b5 = b4.groupby(['team', 'season', 'conf']).mean().rename(
    columns={'blocks':'blocks_mean'}).dropna().reset_index()

# calculate league mean and sd
# add conf
b6 = b5.groupby('season').agg({'blocks_mean':['mean', 'std']}).dropna().reset_index()
b6.columns = ['_'.join(col).strip() for col in b6.columns.values] 
b6.columns = ['season', 'league_blocks_mean', 'league_blocks_std']

# Merge with team-level df
b7 = b6.merge(b5, how='right', on='season')

# calculate z-scores for efg
b7['z.Blk'] = (b7['blocks_mean'] - b7['league_blocks_mean']) / b7['league_blocks_std']

# select meaningful variables
b7 = b7[['team', 'season', 'conf', 'z.Blk']]
display(b7.head(), b7.shape)

   team  season       conf     z.Blk
0  1101    2014  southland -1.646621
1  1101    2015  southland -2.021522
2  1101    2016  southland -0.872251
3  1101    2017  southland -0.522007
4  1101    2018  southland  0.280205

(14311, 4)

In [95]:
### Z-score of off rebounds of each team within each season across all teams

or1 = RegularDetailedResults[['Season', 'WTeamID', 'WOR']].rename(
    columns={'Season':'season', 'WTeamID':'team', 'WOR':'off_reb'})
or2 = RegularDetailedResults[['Season', 'LTeamID', 'LOR']].rename(
    columns={'Season':'season', 'LTeamID':'team', 'LOR':'off_reb'})
or3 = pd.concat([or1,or2])

# calculate team mean by conference and season
or4 = or3.merge(Team_with_Conf, how='left', on=['team', 'season'])
or5 = or4.groupby(['team', 'season', 'conf']).mean().rename(
    columns={'off_reb':'off_reb_mean'}).dropna().reset_index()

# calculate league mean and sd
# add conf
or6 = or5.groupby('season').agg({'off_reb_mean':['mean', 'std']}).dropna().reset_index()
or6.columns = ['_'.join(col).strip() for col in or6.columns.values] 
or6.columns = ['season', 'league_off_reb_mean', 'league_off_reb_std']

# Merge with team-level df
or7 = or6.merge(or5, how='right', on='season')

# calculate z-scores for efg
or7['z.OR'] = (or7['off_reb_mean'] - or7['league_off_reb_mean']) / or7['league_off_reb_std']

# select meaningful variables
or7 = or7[['team', 'season', 'conf', 'z.OR']]
display(or7.head(), or7.shape)

   team  season       conf      z.OR
0  1101    2014  southland -1.762475
1  1101    2015  southland -1.508498
2  1101    2016  southland -1.612294
3  1101    2017  southland -1.775256
4  1101    2018  southland -0.962719

(14311, 4)

In [96]:
### Z-score of def rebounds of each team within each season across all teams

dr1 = RegularDetailedResults[['Season', 'WTeamID', 'WDR']].rename(
    columns={'Season':'season', 'WTeamID':'team', 'WDR':'def_reb'})
dr2 = RegularDetailedResults[['Season', 'LTeamID', 'LDR']].rename(
    columns={'Season':'season', 'LTeamID':'team', 'LDR':'def_reb'})
dr3 = pd.concat([dr1,dr2])

# calculate team mean by conference and season
dr4 = dr3.merge(Team_with_Conf, how='left', on=['team', 'season'])
dr5 = dr4.groupby(['team', 'season', 'conf']).mean().rename(
    columns={'def_reb':'def_reb_mean'}).dropna().reset_index()

# calculate league mean and sd
# add conf
dr6 = dr5.groupby('season').agg({'def_reb_mean':['mean', 'std']}).dropna().reset_index()
dr6.columns = ['_'.join(col).strip() for col in dr6.columns.values] 
dr6.columns = ['season', 'league_def_reb_mean', 'league_def_reb_std']

# Merge with team-level df
dr7 = dr6.merge(dr5, how='right', on='season')

# calculate z-scores for efg
dr7['z.DR'] = (dr7['def_reb_mean'] - dr7['league_def_reb_mean']) / dr7['league_def_reb_std']

# select meaningful variables
dr7 = dr7[['team', 'season', 'conf', 'z.DR']]
display(dr7.head(), dr7.shape)

   team  season       conf      z.DR
0  1101    2014  southland -1.952271
1  1101    2015  southland -2.198331
2  1101    2016  southland -1.345366
3  1101    2017  southland -1.096276
4  1101    2018  southland -0.895202

(14311, 4)

In [97]:
### Z-score of 3pointers of each team within each season across all teams

thr1 = RegularDetailedResults[['Season', 'WTeamID', 'WFGM3', 'WFGA3']].rename(
    columns={'Season':'season', 'WTeamID':'team', 'WFGM3':'FGM3', 'WFGA3':'FGA3'})
thr2 = RegularDetailedResults[['Season', 'LTeamID', 'LFGM3', 'LFGA3']].rename(
    columns={'Season':'season', 'LTeamID':'team', 'LFGM3':'FGM3', 'LFGA3':'FGA3'})
thr3 = pd.concat([thr1,thr2])

# calculate team mean by conference and season
thr4 = thr3.merge(Team_with_Conf, how='left', on=['team', 'season'])
thr5 = thr4.groupby(['team', 'season', 'conf']).mean().rename(
    columns={'FGM3':'fgm3_mean', 'FGA3':'fga3_mean'}).dropna().reset_index()

# calculate league mean and sd
# add conf
thr6 = thr5.groupby('season').agg({'fgm3_mean':['mean', 'std'], 'fga3_mean':['mean', 'std']}).dropna().reset_index()
thr6.columns = ['_'.join(col).strip() for col in thr6.columns.values] 
thr6.columns = ['season', 'league_fgm3_mean', 'league_fgm3_std', 'league_fga3_mean', 'league_fga3_std']

# Merge with team-level df
thr7 = thr6.merge(thr5, how='right', on='season')

# calculate z-scores for efg
thr7['z.3m'] = (thr7['fgm3_mean'] - thr7['league_fgm3_mean']) / thr7['league_fgm3_std']
thr7['z.3a'] = (thr7['fga3_mean'] - thr7['league_fga3_mean']) / thr7['league_fga3_std']
             
# select meaningful variables
thr7 = thr7[['team', 'season', 'conf', 'z.3m', 'z.3a']]
display(thr7.head(), thr7.shape)

   team  season       conf      z.3m      z.3a
0  1101    2014  southland  0.557741  0.051137
1  1101    2015  southland  0.936707  0.405994
2  1101    2016  southland  0.344883 -0.039992
3  1101    2017  southland  0.310787 -0.145395
4  1101    2018  southland -0.177149 -0.061460

(14311, 5)

In [98]:
g5.head()

   team  season       conf    z.grit  z.has_ot
0  1101    2014  southland -1.243557  0.843151
1  1101    2016  southland -1.212715 -0.351353
2  1101    2017  southland  0.388897  1.574663
3  1101    2018  southland  1.284799 -0.450775
4  1101    2020  southland  0.003512  2.265943

In [99]:
# Merge all dataframes together
data_frames = [e7, p7, m10, c2, g5, o7, d7, a7, t7, s7, b7, or7, dr7, thr7]
df_stats = reduce(lambda  left,right: pd.merge(left,right,on=['team', 'season', 'conf'],
                                            how='left'), data_frames)
df_merged = df_stats.merge(winperc, how='left', on=['team', 'season'])

display(df_merged.head(), df_merged.shape)

,team,season,conf,z.efg,z.sa,z.pt,rank,top,mid,bot,z.winsbefore,z.winsafter,z.clutch,z.close,z.grit,z.has_ot,z.off,z.def,z.Ast,z.TO,z.Stl,z.Blk,z.OR,z.DR,z.3m,z.3a,winpercintourney,intourney,seed_num
0,1102,2003,mwc,1.939737,-2.396712,0.067261,12,0,0,1,0.051168,-0.983653,-0.601307,0.174329,NaN,-0.601764,-1.582932,-1.825613,-0.299301,-1.965373,-0.833126,-1.247942,-4.230652,-3.430689,1.250261,0.886153,NaN,NaN,NaN
1,1103,2003,mac,1.206692,-0.392774,0.125825,14,0,0,1,-0.087904,0.677280,0.027084,1.975165,0.646616,2.774770,1.796723,1.829570,0.904340,-1.291090,0.155966,-0.779579,-1.093253,-1.734641,-0.646885,-0.632474,NaN,NaN,NaN
2,1104,2003,sec,-0.867425,0.511890,0.689834,12,0,0,1,0.553623,0.579578,-1.648626,-0.636048,1.258161,-0.004694,0.306560,-0.442917,-0.782907,-0.922760,-0.342116,0.462599,1.032441,0.452083,0.081569,0.577689,0.0,1.0,10.0
3,1105,2003,swac,-1.037090,1.458888,-0.724836,12,0,0,1,-0.895297,-0.788249,-1.369341,0.860032,-1.188020,2.222836,0.696448,1.571300,0.533989,2.090947,1.720545,-0.998879,0.992417,0.007823,1.055114,0.869456,NaN,NaN,NaN
4,1106,2003,swac,-0.369902,-0.215260,0.006656,6,0,1,0,0.294545,-0.299740,0.027084,0.984705,1.258161,0.272517,-0.584922,-0.658963,-1.015038,1.182517,0.994522,-0.087218,0.312017,0.413060,-0.117964,-0.130637,NaN,NaN,NaN

(14311, 29)

In [100]:
seed_check_26 = df_merged[df_merged['season']==2025]

In [101]:
seed_check_26.sort_values(by='seed_num')

,team,season,conf,z.efg,z.sa,z.pt,rank,top,mid,bot,z.winsbefore,z.winsafter,z.clutch,z.close,z.grit,z.has_ot,z.off,z.def,z.Ast,z.TO,z.Stl,z.Blk,z.OR,z.DR,z.3m,z.3a,winpercintourney,intourney,seed_num
13506,3400,2025,sec,0.415432,-0.718180,2.802955,2,1,0,0,1.969883,1.154975,2.304621,-1.051201,-1.227035,-0.161358,1.346040,-2.032849,1.387135,-0.159471,1.984938,2.138526,2.792444,-0.243306,-2.215329,-2.614175,0.800000,1.0,1.0
13483,3376,2025,sec,0.835025,0.791569,2.766559,3,1,0,0,1.942086,1.154975,-2.247377,-2.250033,NaN,-1.118365,1.551177,-1.747280,1.624577,-0.536848,1.420312,2.653176,2.029444,1.706412,-0.692345,-0.918530,0.833333,1.0,1.0
13523,3417,2025,big_ten,1.116142,0.838268,2.554726,1,1,0,0,2.887188,0.738729,2.304621,-1.919439,NaN,-1.118365,1.304024,-1.762956,3.387956,0.576671,0.132311,2.284670,1.699664,2.243963,0.047292,0.044698,0.800000,1.0,1.0
12874,1120,2025,sec,1.637310,1.303775,1.744468,7,0,1,0,1.670620,0.711454,1.293066,0.239145,-1.227035,0.157645,1.998168,0.085822,1.527811,-1.585840,-0.161987,3.128668,0.716799,0.661970,1.418918,1.012323,0.800000,1.0,1.0
12970,1222,2025,big_twelve,1.432854,0.004468,1.924300,9,0,0,1,0.920354,2.211598,-0.296521,-0.447209,-0.979778,2.951665,0.716771,-1.636968,-0.531506,-1.659887,0.449177,1.492417,1.015497,-0.350823,0.732594,-0.201415,0.833333,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13578,3476,2025,nec,-0.078270,0.044808,-0.289823,4,0,1,0,-0.083133,0.996481,1.394221,-0.905074,1.245535,-0.356875,-0.660913,-0.397218,1.483219,0.997993,-1.705544,-0.604709,0.098363,0.221936,0.203777,0.179663,NaN,NaN,NaN
13579,3477,2025,southland,-0.875755,0.445991,-1.331945,18,0,0,1,-1.320767,-1.260165,-1.336977,-0.659725,0.009250,0.567791,-1.052912,0.484844,-0.028117,0.728077,-0.608928,-0.006055,-1.117833,0.190740,0.130760,0.227127,NaN,NaN,NaN
13580,3478,2025,nec,-1.434952,-1.298647,-1.789754,14,0,0,1,-1.406863,-0.488662,-0.426578,-0.905074,0.009250,0.357021,-1.985518,-0.012933,-1.548174,0.939221,-1.238787,-1.515812,-0.931250,-0.586664,-0.328519,-0.219771,NaN,NaN,NaN
13581,3479,2025,nec,-0.279072,-0.927885,-0.899737,12,0,0,1,-1.073240,-1.028714,-1.488711,0.005785,-0.402845,1.605425,-0.800054,0.224126,-1.221367,1.650853,-0.981732,-2.074003,-2.070412,-0.154990,-0.118229,-0.033230,NaN,NaN,NaN
13582,3480,2025,a_sun,-0.961022,0.075122,-0.607906,14,0,0,1,-0.420669,0.186403,-0.426578,-0.727634,-1.227035,1.410868,-0.444892,0.262804,-0.224830,1.284297,0.059290,-0.909615,0.837084,0.152748,-0.612974,-0.039372,NaN,NaN,NaN

In [102]:
# Check for NaN's
print(df_merged.isnull().sum())

team                    0
season                  0
conf                    0
z.efg                   0
z.sa                    0
z.pt                    0
rank                    0
top                     0
mid                     0
bot                     0
z.winsbefore            0
z.winsafter            20
z.clutch               48
z.close                 0
z.grit               3396
z.has_ot                0
z.off                   0
z.def                   0
z.Ast                   0
z.TO                    0
z.Stl                   0
z.Blk                   0
z.OR                    0
z.DR                    0
z.3m                    0
z.3a                    0
winpercintourney    11864
intourney           11864
seed_num            11727
dtype: int64

##### NaN meanings for metrics:

> ##### For winsafter, the team did not win any games after the 100 day mark

> ##### For clutch_z, team did not have any close games that season

> ##### For grit_z, team did not have any games that went into overtime that season

##### For winpercintourney, intourney, and seed_num:
> ##### Most teams do not qualify for the post-season. As such, they should have 0 for those columns, but rather have NaN

##### Because of the reasonings for each NaN, it is reasonable to set all NaN's in the dataframe to 0

In [103]:
# Set all NaN to 0
df_merged = df_merged.fillna(0)

# Check for NaN's
print(df_merged.isnull().sum())
display(df_merged.head())

team                0
season              0
conf                0
z.efg               0
z.sa                0
z.pt                0
rank                0
top                 0
mid                 0
bot                 0
z.winsbefore        0
z.winsafter         0
z.clutch            0
z.close             0
z.grit              0
z.has_ot            0
z.off               0
z.def               0
z.Ast               0
z.TO                0
z.Stl               0
z.Blk               0
z.OR                0
z.DR                0
z.3m                0
z.3a                0
winpercintourney    0
intourney           0
seed_num            0
dtype: int64

,team,season,conf,z.efg,z.sa,z.pt,rank,top,mid,bot,z.winsbefore,z.winsafter,z.clutch,z.close,z.grit,z.has_ot,z.off,z.def,z.Ast,z.TO,z.Stl,z.Blk,z.OR,z.DR,z.3m,z.3a,winpercintourney,intourney,seed_num
0,1102,2003,mwc,1.939737,-2.396712,0.067261,12,0,0,1,0.051168,-0.983653,-0.601307,0.174329,0.000000,-0.601764,-1.582932,-1.825613,-0.299301,-1.965373,-0.833126,-1.247942,-4.230652,-3.430689,1.250261,0.886153,0.0,0.0,0.0
1,1103,2003,mac,1.206692,-0.392774,0.125825,14,0,0,1,-0.087904,0.677280,0.027084,1.975165,0.646616,2.774770,1.796723,1.829570,0.904340,-1.291090,0.155966,-0.779579,-1.093253,-1.734641,-0.646885,-0.632474,0.0,0.0,0.0
2,1104,2003,sec,-0.867425,0.511890,0.689834,12,0,0,1,0.553623,0.579578,-1.648626,-0.636048,1.258161,-0.004694,0.306560,-0.442917,-0.782907,-0.922760,-0.342116,0.462599,1.032441,0.452083,0.081569,0.577689,0.0,1.0,10.0
3,1105,2003,swac,-1.037090,1.458888,-0.724836,12,0,0,1,-0.895297,-0.788249,-1.369341,0.860032,-1.188020,2.222836,0.696448,1.571300,0.533989,2.090947,1.720545,-0.998879,0.992417,0.007823,1.055114,0.869456,0.0,0.0,0.0
4,1106,2003,swac,-0.369902,-0.215260,0.006656,6,0,1,0,0.294545,-0.299740,0.027084,0.984705,1.258161,0.272517,-0.584922,-0.658963,-1.015038,1.182517,0.994522,-0.087218,0.312017,0.413060,-0.117964,-0.130637,0.0,0.0,0.0

In [104]:
# Convert seeding to seed strength
# 17 - seed (so 1 seed = strength 16)
# more easily interpreted

df_merged['seed_strength'] = 17 - df_merged['seed_num']
df_merged = df_merged.drop(['seed_num'],axis=1)

In [105]:
### Adding conference ranking and converting to conference strength
### Similar to seed strength
### Data only available from 2022 - 2026

max_rank_by_season = ConfRank.groupby(['season','M_W'])['Rank'].max().reset_index()
max_rank_by_season = max_rank_by_season.rename(columns={'Rank': 'max_rank'})

ConfRank_w_max = ConfRank.merge(max_rank_by_season, how='left', on=['season','M_W'])

ConfRank_w_max['conf_strength'] = (ConfRank_w_max['max_rank']+1) - ConfRank_w_max['Rank']

Conf_Strength = ConfRank_w_max.drop(['Rank','Conference','max_rank'],axis=1)

display(Conf_Strength.sort_values(by=['conf','season'],ascending=False).head(), Conf_Strength.shape)

     season conf M_W  conf_strength
6      2026  wcc   M             25
167    2026  wcc   W             24
37     2025  wcc   M             25
202    2025  wcc   W             20
72     2024  wcc   M             23

(320, 4)

In [106]:
# Add M_W differentiator to the larger dataset
df_merged['M_W'] = df_merged['team'].astype(int).apply(
    lambda x: 'M' if 1000 <= x < 3000 else 'W'
)
df_merged.shape

(14311, 30)

In [107]:
# Merge with broader dataset

df_merged = df_merged.merge(Conf_Strength, how='left', on=['conf','season', 'M_W'])
display(df_merged.head(),df_merged.shape)

,team,season,conf,z.efg,z.sa,z.pt,rank,top,mid,bot,z.winsbefore,z.winsafter,z.clutch,z.close,z.grit,z.has_ot,z.off,z.def,z.Ast,z.TO,z.Stl,z.Blk,z.OR,z.DR,z.3m,z.3a,winpercintourney,intourney,seed_strength,M_W,conf_strength
0,1102,2003,mwc,1.939737,-2.396712,0.067261,12,0,0,1,0.051168,-0.983653,-0.601307,0.174329,0.000000,-0.601764,-1.582932,-1.825613,-0.299301,-1.965373,-0.833126,-1.247942,-4.230652,-3.430689,1.250261,0.886153,0.0,0.0,17.0,M,NaN
1,1103,2003,mac,1.206692,-0.392774,0.125825,14,0,0,1,-0.087904,0.677280,0.027084,1.975165,0.646616,2.774770,1.796723,1.829570,0.904340,-1.291090,0.155966,-0.779579,-1.093253,-1.734641,-0.646885,-0.632474,0.0,0.0,17.0,M,NaN
2,1104,2003,sec,-0.867425,0.511890,0.689834,12,0,0,1,0.553623,0.579578,-1.648626,-0.636048,1.258161,-0.004694,0.306560,-0.442917,-0.782907,-0.922760,-0.342116,0.462599,1.032441,0.452083,0.081569,0.577689,0.0,1.0,7.0,M,NaN
3,1105,2003,swac,-1.037090,1.458888,-0.724836,12,0,0,1,-0.895297,-0.788249,-1.369341,0.860032,-1.188020,2.222836,0.696448,1.571300,0.533989,2.090947,1.720545,-0.998879,0.992417,0.007823,1.055114,0.869456,0.0,0.0,17.0,M,NaN
4,1106,2003,swac,-0.369902,-0.215260,0.006656,6,0,1,0,0.294545,-0.299740,0.027084,0.984705,1.258161,0.272517,-0.584922,-0.658963,-1.015038,1.182517,0.994522,-0.087218,0.312017,0.413060,-0.117964,-0.130637,0.0,0.0,17.0,M,NaN

(14311, 31)

In [108]:
# Select data from 2022 - 2026 
# 22-25 will be used for training
# 26 included here so that the data is available later

df_full = df_merged.loc[(df_merged['season'].between(2022,2026))]
display(df_full.head(), df_full.shape)

,team,season,conf,z.efg,z.sa,z.pt,rank,top,mid,bot,z.winsbefore,z.winsafter,z.clutch,z.close,z.grit,z.has_ot,z.off,z.def,z.Ast,z.TO,z.Stl,z.Blk,z.OR,z.DR,z.3m,z.3a,winpercintourney,intourney,seed_strength,M_W,conf_strength
10697,1101,2022,wac,-0.045659,0.341508,0.652882,8,0,0,1,0.763072,0.728473,0.489360,1.114148,-0.378251,1.101226,0.943241,0.202626,0.648655,-0.682630,2.193933,-1.412967,-0.094237,-1.595220,0.085824,0.260685,0.0,0.0,17.0,M,18.0
10698,1102,2022,mwc,0.575808,-1.261292,-0.880197,13,0,0,1,0.158470,-1.266570,1.012846,0.012930,0.000000,-1.176542,-1.191500,-0.186385,-0.146769,-0.827191,-1.033984,-0.148112,-2.215604,-2.048607,0.384044,0.322057,0.0,0.0,17.0,M,25.0
10699,1103,2022,mac,1.283811,-0.813785,0.701176,4,0,1,0,1.169411,1.095981,0.489360,0.877327,-1.182384,-0.463301,0.357069,-0.492648,-0.631498,-1.169474,-1.031829,-0.087983,-0.581809,0.131697,0.715933,0.354015,0.0,1.0,4.0,M,14.0
10700,1104,2022,sec,0.400822,2.566417,0.496933,7,0,1,0,1.138905,0.728473,0.413018,1.435336,-1.182384,-0.686189,1.969446,1.509372,0.927486,0.195126,-0.032216,1.477683,1.480216,0.756175,1.686757,2.493891,0.0,1.0,11.0,M,30.0
10701,1105,2022,swac,-1.364236,-1.079965,-0.693320,13,0,0,1,-1.088031,1.300152,0.031310,1.701464,1.230014,-0.417286,-0.829288,-0.028526,-1.642512,-0.165584,-0.010697,0.011659,0.312990,0.358990,-1.637459,-1.504765,0.0,0.0,17.0,M,1.0

(3614, 31)

In [109]:
# Save merged df to csv for loading in EDA notebook
df_full.to_csv('df_full.csv', index=False)

### Games to Predict

In [110]:
### Create dataset of each team in the post-season by season
games_to_predict = pd.concat([SampleSubmission['ID'], SampleSubmission['ID'].str.split('_', expand=True).rename(
    columns={0:'season', 1:'team1', 2:'team2'})], axis=1)

In [111]:
# Save games_to_predict to csv for loading in Log Reg notebook
games_to_predict.to_csv('games_to_predict.csv', index=False)