### Load relevant libraries

In [48]:
# Load relevant libraries
import os
import pandas as pd
pd.set_option('display.max_columns', None)

import numpy as np

### Read in the data

In [49]:
# Set working directory (necessary until 2019 data comes out)
path = 'C:/Users/caanm/OneDrive/Documents/Project Portfolio/March Madness 2026/2026 Data'
os.chdir(path)

In [50]:
# Read in datasets
M_TourneyCompactResults = pd.read_csv("MNCAATourneyCompactResults.csv", sep=',', index_col=None)
W_TourneyCompactResults = pd.read_csv("WNCAATourneyCompactResults.csv", sep=',', index_col=None)

M_RegularCompactResults = pd.read_csv("MRegularSeasonCompactResults.csv", sep=',', index_col=None)
W_RegularCompactResults = pd.read_csv("WRegularSeasonCompactResults.csv", sep=',', index_col=None)

df = pd.read_csv('df_full.csv', sep=',', index_col=None)

In [51]:
TourneyCompactResults = pd.concat([M_TourneyCompactResults,W_TourneyCompactResults])
RegularCompactResults = pd.concat([M_RegularCompactResults,W_RegularCompactResults])

### Prep the Data

In [52]:
# Create a team x team dataset for predictions
# essentially a dataset of all possible matchups
dyad_tourney = TourneyCompactResults[TourneyCompactResults['Season'].between(2022,2025)]
dyad_tourney.head()

# create dyad
pd.options.mode.chained_assignment = None  # default='warn'

dyad_tourney['team_a'] = np.where(dyad_tourney['WTeamID'] < dyad_tourney['LTeamID'], dyad_tourney['WTeamID'], dyad_tourney['LTeamID'])
dyad_tourney['team_b'] = np.where(dyad_tourney['LTeamID'] < dyad_tourney['WTeamID'], dyad_tourney['WTeamID'], dyad_tourney['LTeamID'])
dyad_tourney['team_a_win'] = np.where(dyad_tourney['team_a'] == dyad_tourney['WTeamID'], 1, 0)

display(dyad_tourney.head(), dyad_tourney.shape)

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,team_a,team_b,team_a_win
2317,2022,134,1231,66,1461,58,N,0,1231,1461,1
2318,2022,134,1411,76,1394,67,N,0,1394,1411,0
2319,2022,135,1323,89,1353,87,N,2,1323,1353,1
2320,2022,135,1460,93,1136,82,N,0,1136,1460,0
2321,2022,136,1116,75,1436,71,N,0,1116,1436,1

(536, 11)

In [53]:
# do the same for the regular season matchups
dyad_regular = RegularCompactResults[RegularCompactResults['Season'].between(2022,2026)]
dyad_regular.head()

# create dyad
pd.options.mode.chained_assignment = None  # default='warn'

dyad_regular['team_a'] = np.where(dyad_regular['WTeamID'] < dyad_regular['LTeamID'], dyad_regular['WTeamID'], dyad_regular['LTeamID'])
dyad_regular['team_b'] = np.where(dyad_regular['LTeamID'] < dyad_regular['WTeamID'], dyad_regular['WTeamID'], dyad_regular['LTeamID'])
dyad_regular['team_a_win'] = np.where(dyad_regular['team_a'] == dyad_regular['WTeamID'], 1, 0)

display(dyad_regular.head(), dyad_regular.shape)

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,team_a,team_b,team_a_win
170735,2022,8,1104,93,1256,64,H,0,1104,1256,1
170736,2022,8,1105,82,1398,73,H,0,1105,1398,1
170737,2022,8,1110,77,1265,73,H,1,1110,1265,1
170738,2022,8,1112,81,1319,52,H,0,1112,1319,1
170739,2022,8,1113,76,1339,60,H,0,1113,1339,1

(54613, 11)

In [54]:
# Merge for a full dyad dataset
dyad_full = pd.concat([dyad_tourney,dyad_regular]).reset_index()[['Season','team_a', 'team_b', 'team_a_win']]
display(dyad_full.head(), dyad_full.shape)

   Season  team_a  team_b  team_a_win
0    2022    1231    1461           1
1    2022    1394    1411           0
2    2022    1323    1353           1
3    2022    1136    1460           0
4    2022    1116    1436           1

(55149, 4)

In [55]:
display(df.head(), df.shape)

,team,season,conf,z.efg,z.sa,z.pt,rank,top,mid,bot,z.winsbefore,z.winsafter,z.clutch,z.close,z.grit,z.has_ot,z.off,z.def,z.Ast,z.TO,z.Stl,z.Blk,z.OR,z.DR,z.3m,z.3a,winpercintourney,intourney,seed_strength,M_W,conf_strength
0,1101,2022,wac,-0.045659,0.341508,0.652882,8,0,0,1,0.763072,0.728473,0.489360,1.114148,-0.378251,1.101226,0.943241,0.202626,0.648655,-0.682630,2.193933,-1.412967,-0.094237,-1.595220,0.085824,0.260685,0.0,0.0,17.0,M,18.0
1,1102,2022,mwc,0.575808,-1.261292,-0.880197,13,0,0,1,0.158470,-1.266570,1.012846,0.012930,0.000000,-1.176542,-1.191500,-0.186385,-0.146769,-0.827191,-1.033984,-0.148112,-2.215604,-2.048607,0.384044,0.322057,0.0,0.0,17.0,M,25.0
2,1103,2022,mac,1.283811,-0.813785,0.701176,4,0,1,0,1.169411,1.095981,0.489360,0.877327,-1.182384,-0.463301,0.357069,-0.492648,-0.631498,-1.169474,-1.031829,-0.087983,-0.581809,0.131697,0.715933,0.354015,0.0,1.0,4.0,M,14.0
3,1104,2022,sec,0.400822,2.566417,0.496933,7,0,1,0,1.138905,0.728473,0.413018,1.435336,-1.182384,-0.686189,1.969446,1.509372,0.927486,0.195126,-0.032216,1.477683,1.480216,0.756175,1.686757,2.493891,0.0,1.0,11.0,M,30.0
4,1105,2022,swac,-1.364236,-1.079965,-0.693320,13,0,0,1,-1.088031,1.300152,0.031310,1.701464,1.230014,-0.417286,-0.829288,-0.028526,-1.642512,-0.165584,-0.010697,0.011659,0.312990,0.358990,-1.637459,-1.504765,0.0,0.0,17.0,M,1.0

(3614, 31)

In [56]:
# Assign season stats from df_merged to dyad teams
team_a_stats = df.copy()
team_a_stats.columns = ['team_a', 'Season', 'conf_a', 'z.efg_a', 'z.sa_a', 'z.pt_a', 
              'rank_a', 'top_a', 'mid_a', 'bot_a', 'z.winsbefore_a', 'z.winsafter_a', 
              'z.clutch_a', 'z.close_a', 'z.grit_a', 'z.has_ot_a', 
              'z.off_a', 'z.def_a', 'z.ast_a', 'z.to_a', 'z.stl_a', 'z.blk_a', 'z.or_a', 
              'z.dr_a', 'z.3m_a', 'z.3a_a', 'winpercintourney_a','intourney_a','seed_strength_a', 
              'M_W_a', 'conf_strength_a']
print(team_a_stats.columns)

team_b_stats = df.copy()
team_b_stats.columns = ['team_b', 'Season', 'conf_b', 'z.efg_b', 'z.sa_b', 'z.pt_b', 
              'rank_b', 'top_b', 'mid_b', 'bot_b', 'z.winsbefore_b', 'z.winsafter_b', 
              'z.clutch_b', 'z.close_b', 'z.grit_b', 'z.has_ot_b', 
              'z.off_b', 'z.def_b', 'z.ast_b', 'z.to_b', 'z.stl_b', 'z.blk_b', 'z.or_b', 
              'z.dr_b', 'z.3m_b', 'z.3a_b', 'winpercintourney_b','intourney_b','seed_strength_b', 
              'M_W_b', 'conf_strength_b']
print(team_b_stats.columns)

Index(['team_a', 'Season', 'conf_a', 'z.efg_a', 'z.sa_a', 'z.pt_a', 'rank_a',
       'top_a', 'mid_a', 'bot_a', 'z.winsbefore_a', 'z.winsafter_a',
       'z.clutch_a', 'z.close_a', 'z.grit_a', 'z.has_ot_a', 'z.off_a',
       'z.def_a', 'z.ast_a', 'z.to_a', 'z.stl_a', 'z.blk_a', 'z.or_a',
       'z.dr_a', 'z.3m_a', 'z.3a_a', 'winpercintourney_a', 'intourney_a',
       'seed_strength_a', 'M_W_a', 'conf_strength_a'],
      dtype='object')
Index(['team_b', 'Season', 'conf_b', 'z.efg_b', 'z.sa_b', 'z.pt_b', 'rank_b',
       'top_b', 'mid_b', 'bot_b', 'z.winsbefore_b', 'z.winsafter_b',
       'z.clutch_b', 'z.close_b', 'z.grit_b', 'z.has_ot_b', 'z.off_b',
       'z.def_b', 'z.ast_b', 'z.to_b', 'z.stl_b', 'z.blk_b', 'z.or_b',
       'z.dr_b', 'z.3m_b', 'z.3a_b', 'winpercintourney_b', 'intourney_b',
       'seed_strength_b', 'M_W_b', 'conf_strength_b'],
      dtype='object')

In [57]:
team_a_stats.head()

,team_a,Season,conf_a,z.efg_a,z.sa_a,z.pt_a,rank_a,top_a,mid_a,bot_a,z.winsbefore_a,z.winsafter_a,z.clutch_a,z.close_a,z.grit_a,z.has_ot_a,z.off_a,z.def_a,z.ast_a,z.to_a,z.stl_a,z.blk_a,z.or_a,z.dr_a,z.3m_a,z.3a_a,winpercintourney_a,intourney_a,seed_strength_a,M_W_a,conf_strength_a
0,1101,2022,wac,-0.045659,0.341508,0.652882,8,0,0,1,0.763072,0.728473,0.489360,1.114148,-0.378251,1.101226,0.943241,0.202626,0.648655,-0.682630,2.193933,-1.412967,-0.094237,-1.595220,0.085824,0.260685,0.0,0.0,17.0,M,18.0
1,1102,2022,mwc,0.575808,-1.261292,-0.880197,13,0,0,1,0.158470,-1.266570,1.012846,0.012930,0.000000,-1.176542,-1.191500,-0.186385,-0.146769,-0.827191,-1.033984,-0.148112,-2.215604,-2.048607,0.384044,0.322057,0.0,0.0,17.0,M,25.0
2,1103,2022,mac,1.283811,-0.813785,0.701176,4,0,1,0,1.169411,1.095981,0.489360,0.877327,-1.182384,-0.463301,0.357069,-0.492648,-0.631498,-1.169474,-1.031829,-0.087983,-0.581809,0.131697,0.715933,0.354015,0.0,1.0,4.0,M,14.0
3,1104,2022,sec,0.400822,2.566417,0.496933,7,0,1,0,1.138905,0.728473,0.413018,1.435336,-1.182384,-0.686189,1.969446,1.509372,0.927486,0.195126,-0.032216,1.477683,1.480216,0.756175,1.686757,2.493891,0.0,1.0,11.0,M,30.0
4,1105,2022,swac,-1.364236,-1.079965,-0.693320,13,0,0,1,-1.088031,1.300152,0.031310,1.701464,1.230014,-0.417286,-0.829288,-0.028526,-1.642512,-0.165584,-0.010697,0.011659,0.312990,0.358990,-1.637459,-1.504765,0.0,0.0,17.0,M,1.0

##### Save team stats to csv for loading in Logistic Regression notebook
##### Keep only 2026 data, need stats for predictions later

In [58]:
team_a_2026 = team_a_stats.copy()
team_a_2026 = team_a_2026[team_a_2026['Season'] == 2026]
team_a_2026 = team_a_2026.drop(['winpercintourney_a','intourney_a'],axis=1)


team_b_2026 = team_b_stats.copy()
team_b_2026 = team_b_2026[team_b_2026['Season'] == 2026]
team_b_2026 = team_b_2026.drop(['winpercintourney_b', 'intourney_b'],axis=1)

display(team_a_2026.shape, team_b_2026.shape)

(728, 29)

(728, 29)

In [59]:
team_a_2026.head().sort_values(by='seed_strength_a')

,team_a,Season,conf_a,z.efg_a,z.sa_a,z.pt_a,rank_a,top_a,mid_a,bot_a,z.winsbefore_a,z.winsafter_a,z.clutch_a,z.close_a,z.grit_a,z.has_ot_a,z.off_a,z.def_a,z.ast_a,z.to_a,z.stl_a,z.blk_a,z.or_a,z.dr_a,z.3m_a,z.3a_a,seed_strength_a,M_W_a,conf_strength_a
2888,1103,2026,mac,2.088606,1.858487,1.446969,4,0,1,0,1.316575,2.119790,0.512228,-0.948143,0.000000,-1.178771,2.058478,0.616427,2.015763,-0.916825,-0.042117,-0.357421,0.220382,1.026064,2.289566,1.692553,5.0,M,16.0
2889,1104,2026,sec,1.132784,3.593371,0.973787,11,0,0,1,1.010385,1.095610,1.247357,0.064381,1.252030,-0.451174,2.646483,1.889455,1.244654,-1.294037,-0.506262,1.920422,0.580700,2.029960,3.329134,3.447199,13.0,M,31.0
2886,1101,2026,wac,-0.162759,-1.197764,-0.653195,10,0,0,1,-0.693469,-0.338242,0.022142,0.244385,-1.275128,-0.402667,-0.240937,0.526532,-0.337955,0.118533,1.300330,-0.678488,-0.469026,-2.115358,-0.808466,-0.859285,17.0,M,21.0
2887,1102,2026,mwc,-0.175115,-1.203686,-2.076803,20,0,0,1,-1.763332,-1.976930,-1.203073,-1.285651,0.000000,-1.178771,-1.018115,1.379356,-0.504111,0.085482,-0.970406,-0.878070,-1.941526,-1.012617,-0.245519,-0.007985,17.0,M,26.0
2890,1105,2026,swac,0.404848,-1.220059,-0.259354,3,1,0,0,-0.093441,0.299025,0.022142,-0.475631,1.252030,-0.402667,0.175851,0.526532,-0.910779,-0.904610,-0.641934,-0.504938,-0.853365,-0.154929,-0.302665,-0.752100,17.0,M,4.0

##### Dropping the winpercintourney and intourney variables as these will be 0 for 2026
##### Calculate the average winpercentage from 2022-2025 for each team and add in to account for historical performance

In [60]:
hist_tourney = df[df['season'].between(2022,2025)][['team', 'winpercintourney', 'intourney']].copy()
display(hist_tourney.sort_values(by='winpercintourney', ascending=False).head(), hist_tourney.shape)

      team  winpercintourney  intourney
1229  3261               1.0        1.0
2062  3376               1.0        1.0
770   1163               1.0        1.0
2579  3163               1.0        1.0
2249  1196               1.0        1.0

(2886, 3)

##### Calculate the average winpercintourney over the last 4 seasons ('22 - '25)

In [61]:
hist_tourney = hist_tourney.groupby('team')['winpercintourney'].mean().reset_index()
display(hist_tourney.sort_values(by='winpercintourney', ascending=False).head(), hist_tourney.shape)

     team  winpercintourney
629  3376          0.908333
421  3163          0.825000
518  3261          0.750000
114  1222          0.729167
74   1181          0.712500

(730, 2)

##### Merge back in to the team-level data

In [62]:
team_a_2026_full = team_a_2026.merge(hist_tourney, how='left', left_on=['team_a'], right_on=['team']).drop(
    ['team'],axis=1).rename(
    columns={'winpercintourney':'winpercintourney_a','intourney':'intourney_a'})
display(team_a_2026_full.sort_values(by='winpercintourney_a', ascending=False).head(), team_a_2026.shape)

,team_a,Season,conf_a,z.efg_a,z.sa_a,z.pt_a,rank_a,top_a,mid_a,bot_a,z.winsbefore_a,z.winsafter_a,z.clutch_a,z.close_a,z.grit_a,z.has_ot_a,z.off_a,z.def_a,z.ast_a,z.to_a,z.stl_a,z.blk_a,z.or_a,z.dr_a,z.3m_a,z.3a_a,seed_strength_a,M_W_a,conf_strength_a,winpercintourney_a
627,3376,2026,sec,1.938516,0.217357,3.279811,1,1,0,0,2.031479,1.607700,1.247357,-1.365064,-1.275128,-0.493973,1.987962,-1.733937,2.070842,-0.318991,1.226403,2.988519,1.303456,1.966365,-0.521235,-1.257472,16.0,W,31.0,0.908333
420,3163,2026,big_east,2.665513,1.751825,4.430293,1,1,0,0,2.397243,2.119790,2.472573,-2.318028,0.000000,-1.178771,2.287878,-2.806839,4.585045,-0.288561,4.737937,1.794088,0.218263,0.658120,1.469928,0.619486,16.0,W,27.0,0.825000
516,3261,2026,sec,1.831712,1.017174,3.884573,3,1,0,0,1.826650,0.949298,-0.794668,-1.623158,0.000000,-1.178771,2.980319,-1.321945,2.208540,0.473472,2.350010,2.506153,3.589356,2.956633,-0.683232,-1.546200,15.0,W,31.0,0.750000
113,1222,2026,big_twelve,0.759417,1.200990,1.667112,2,1,0,0,2.000998,0.481102,-0.327919,-0.412101,1.252030,-0.493973,0.877559,-1.036760,0.606383,-1.840520,0.235109,0.660909,0.964333,-0.344867,1.075129,0.932312,15.0,M,29.0,0.729167
74,1181,2026,acc,1.531677,0.768191,2.223797,1,1,0,0,2.000998,2.119790,1.072327,-0.412101,0.000000,-1.178771,1.502384,-0.995013,1.604288,-1.039181,0.268712,0.048380,1.015201,1.922757,1.246781,1.114188,16.0,M,28.0,0.712500

(728, 29)

In [63]:
team_b_2026_full = team_b_2026.merge(hist_tourney, how='left', left_on=['team_b'], right_on=['team']).drop(
    ['team'],axis=1).rename(
    columns={'winpercintourney':'winpercintourney_b','intourney':'intourney_b'})
display(team_b_2026_full.sort_values(by='winpercintourney_b', ascending=False).head(), team_b_2026.shape)

,team_b,Season,conf_b,z.efg_b,z.sa_b,z.pt_b,rank_b,top_b,mid_b,bot_b,z.winsbefore_b,z.winsafter_b,z.clutch_b,z.close_b,z.grit_b,z.has_ot_b,z.off_b,z.def_b,z.ast_b,z.to_b,z.stl_b,z.blk_b,z.or_b,z.dr_b,z.3m_b,z.3a_b,seed_strength_b,M_W_b,conf_strength_b,winpercintourney_b
627,3376,2026,sec,1.938516,0.217357,3.279811,1,1,0,0,2.031479,1.607700,1.247357,-1.365064,-1.275128,-0.493973,1.987962,-1.733937,2.070842,-0.318991,1.226403,2.988519,1.303456,1.966365,-0.521235,-1.257472,16.0,W,31.0,0.908333
420,3163,2026,big_east,2.665513,1.751825,4.430293,1,1,0,0,2.397243,2.119790,2.472573,-2.318028,0.000000,-1.178771,2.287878,-2.806839,4.585045,-0.288561,4.737937,1.794088,0.218263,0.658120,1.469928,0.619486,16.0,W,27.0,0.825000
516,3261,2026,sec,1.831712,1.017174,3.884573,3,1,0,0,1.826650,0.949298,-0.794668,-1.623158,0.000000,-1.178771,2.980319,-1.321945,2.208540,0.473472,2.350010,2.506153,3.589356,2.956633,-0.683232,-1.546200,15.0,W,31.0,0.750000
113,1222,2026,big_twelve,0.759417,1.200990,1.667112,2,1,0,0,2.000998,0.481102,-0.327919,-0.412101,1.252030,-0.493973,0.877559,-1.036760,0.606383,-1.840520,0.235109,0.660909,0.964333,-0.344867,1.075129,0.932312,15.0,M,29.0,0.729167
74,1181,2026,acc,1.531677,0.768191,2.223797,1,1,0,0,2.000998,2.119790,1.072327,-0.412101,0.000000,-1.178771,1.502384,-0.995013,1.604288,-1.039181,0.268712,0.048380,1.015201,1.922757,1.246781,1.114188,16.0,M,28.0,0.712500

(728, 29)

In [64]:
team_a_2026_full.to_csv('team_a_2026.csv', index=False)
team_b_2026_full.to_csv('team_b_2026.csv', index=False)

In [65]:
# Merge team stats to dyad df

teamxteam1 = dyad_full.merge(team_a_stats, how='left', on=['team_a','Season'])
teamxteam2 = teamxteam1.merge(team_b_stats, how='left', on=['team_b','Season'])

display(teamxteam2.head(), teamxteam2.shape)
teamxteam2.columns

,Season,team_a,team_b,team_a_win,conf_a,z.efg_a,z.sa_a,z.pt_a,rank_a,top_a,mid_a,bot_a,z.winsbefore_a,z.winsafter_a,z.clutch_a,z.close_a,z.grit_a,z.has_ot_a,z.off_a,z.def_a,z.ast_a,z.to_a,z.stl_a,z.blk_a,z.or_a,z.dr_a,z.3m_a,z.3a_a,winpercintourney_a,intourney_a,seed_strength_a,M_W_a,conf_strength_a,conf_b,z.efg_b,z.sa_b,z.pt_b,rank_b,top_b,mid_b,bot_b,z.winsbefore_b,z.winsafter_b,z.clutch_b,z.close_b,z.grit_b,z.has_ot_b,z.off_b,z.def_b,z.ast_b,z.to_b,z.stl_b,z.blk_b,z.or_b,z.dr_b,z.3m_b,z.3a_b,winpercintourney_b,intourney_b,seed_strength_b,M_W_b,conf_strength_b
0,2022,1231,1461,1,big_ten,1.053549,-0.607257,0.755469,6,0,1,0,1.042430,-0.271965,-0.350398,1.314369,-1.182384,0.235674,0.688429,-0.201932,1.085143,-0.873188,-0.853868,1.719919,-0.810542,1.204888,-0.265326,-0.565570,0.500000,1.0,5.0,M,31.0,mwc,0.930270,-0.140585,0.839178,3,1,0,0,1.714960,0.177212,1.488742,1.102677,1.230014,1.592510,0.747340,-0.243116,-0.953000,-1.180462,-2.110188,-1.086351,-1.111711,1.467315,0.605711,0.650558,0.0,1.0,5.0,M,25.0
1,2022,1394,1411,0,southland,0.073130,0.040983,0.384481,3,1,0,0,0.621175,0.728473,1.405460,-0.782394,-1.182384,-0.441013,1.032970,0.636364,0.380055,0.044030,0.742483,-1.532795,1.246771,-0.045570,-0.401978,-0.403002,0.000000,1.0,1.0,M,3.0,swac,0.296725,-0.358098,0.519206,3,1,0,0,0.148187,1.389988,0.489360,0.991790,1.230014,-0.417286,0.348464,-0.273772,-1.024041,0.197746,-0.936033,1.749170,0.935511,0.999543,-0.484343,-0.530129,0.5,1.0,1.0,M,1.0
2,2022,1323,1353,1,acc,1.632207,0.271003,0.684353,9,0,0,1,0.919904,0.682535,1.072333,1.220717,1.230014,-0.153197,0.756472,-0.039074,0.694953,-1.669842,-1.281732,-1.302372,-1.609499,1.159409,1.552872,0.952740,0.666667,1.0,6.0,M,28.0,big_ten,0.678785,-0.461655,0.305833,5,0,1,0,1.094163,-0.075450,0.207483,1.907498,0.023815,-0.153197,0.147626,-0.223668,1.099358,-1.128904,0.113560,0.721609,0.002911,0.148010,-0.300350,-0.564576,0.0,1.0,6.0,M,31.0
3,2022,1136,1460,0,nec,0.177497,1.883798,0.432286,4,0,1,0,0.473367,1.749329,0.794727,-0.427558,-1.182384,0.249939,1.435620,1.012408,0.346625,-0.207507,-0.462605,0.976943,0.843963,1.471529,1.080599,1.724247,0.000000,1.0,1.0,M,4.0,horizon,1.186001,-0.068391,0.494710,8,0,0,1,0.457449,0.850976,-0.176895,0.991790,0.000000,-1.176542,1.242073,0.724553,0.568484,-0.619111,-0.834305,-0.298402,0.021704,-0.220266,-0.153010,-0.303613,0.5,1.0,1.0,M,7.0
4,2022,1116,1436,1,sec,0.204001,0.545169,1.126852,3,1,0,0,1.756346,0.728473,0.031310,0.024053,1.230014,0.784870,1.512032,0.224152,0.659659,-0.619111,0.437299,0.959392,0.421182,1.143591,-0.115571,0.120142,0.750000,1.0,13.0,M,30.0,aec,2.151199,0.228052,1.865914,2,1,0,0,1.508028,1.794247,0.031310,-0.560621,-1.182384,-0.484279,1.181447,-1.060603,1.146876,-1.796202,-1.182162,-0.754535,-1.729654,1.451512,1.397191,0.936593,0.0,1.0,4.0,M,6.0

(55149, 62)

Index(['Season', 'team_a', 'team_b', 'team_a_win', 'conf_a', 'z.efg_a',
       'z.sa_a', 'z.pt_a', 'rank_a', 'top_a', 'mid_a', 'bot_a',
       'z.winsbefore_a', 'z.winsafter_a', 'z.clutch_a', 'z.close_a',
       'z.grit_a', 'z.has_ot_a', 'z.off_a', 'z.def_a', 'z.ast_a', 'z.to_a',
       'z.stl_a', 'z.blk_a', 'z.or_a', 'z.dr_a', 'z.3m_a', 'z.3a_a',
       'winpercintourney_a', 'intourney_a', 'seed_strength_a', 'M_W_a',
       'conf_strength_a', 'conf_b', 'z.efg_b', 'z.sa_b', 'z.pt_b', 'rank_b',
       'top_b', 'mid_b', 'bot_b', 'z.winsbefore_b', 'z.winsafter_b',
       'z.clutch_b', 'z.close_b', 'z.grit_b', 'z.has_ot_b', 'z.off_b',
       'z.def_b', 'z.ast_b', 'z.to_b', 'z.stl_b', 'z.blk_b', 'z.or_b',
       'z.dr_b', 'z.3m_b', 'z.3a_b', 'winpercintourney_b', 'intourney_b',
       'seed_strength_b', 'M_W_b', 'conf_strength_b'],
      dtype='object')

In [66]:
# Filter out 2026 for training data
teamxteam2 = teamxteam2[teamxteam2['Season'] != 2026]

### Calculating difference in performance between teams

##### The difference in performance statistics will be used rather than incorporating both teams' sets
##### The effect a variable has on increasing team a's odds of winning should have a proportionate effect on decreasing team b's odds
##### Including both, for example, winsbefore_a and winsbefore_b, causes
> ##### Extra variance
> ##### Multicollinearity
> ##### Weaker statistical power
##### Instead, I will include winsbefore_diff = winsbefore_a - winsbefore_b
> ##### This allows me to estimate one coefficient instead of two
##### As a reminder, many metrics are z-scores. So the interpretation for differences becomes relative performance measured in standard deviations of advantage

In [67]:
### Calculate differences
teamxteam2['efg_diff'] = teamxteam2['z.efg_a'] - teamxteam2['z.efg_b']
teamxteam2['sa_diff'] = teamxteam2['z.sa_a'] - teamxteam2['z.sa_b']
teamxteam2['pt_diff'] = teamxteam2['z.pt_a'] - teamxteam2['z.pt_b']
teamxteam2['rank_diff'] = teamxteam2['rank_a'] - teamxteam2['rank_b']
teamxteam2['winsbefore_diff'] = teamxteam2['z.winsbefore_a'] - teamxteam2['z.winsbefore_b']
teamxteam2['winsafter_diff'] = teamxteam2['z.winsafter_a'] - teamxteam2['z.winsafter_b']
teamxteam2['clutch_diff'] = teamxteam2['z.clutch_a'] - teamxteam2['z.clutch_b']
teamxteam2['close_diff'] = teamxteam2['z.close_a'] - teamxteam2['z.close_b']
teamxteam2['grit_diff'] = teamxteam2['z.grit_a'] - teamxteam2['z.grit_b']
teamxteam2['has_ot_diff'] = teamxteam2['z.has_ot_a'] - teamxteam2['z.has_ot_b']
teamxteam2['off_diff'] = teamxteam2['z.off_a'] - teamxteam2['z.off_b']
teamxteam2['def_diff'] = teamxteam2['z.def_a'] - teamxteam2['z.def_b']
teamxteam2['ast_diff'] = teamxteam2['z.ast_a'] - teamxteam2['z.ast_b']
teamxteam2['to_diff'] = teamxteam2['z.to_a'] - teamxteam2['z.to_b']
teamxteam2['stl_diff'] = teamxteam2['z.stl_a'] - teamxteam2['z.stl_b']
teamxteam2['blk_diff'] = teamxteam2['z.blk_a'] - teamxteam2['z.blk_b']
teamxteam2['or_diff'] = teamxteam2['z.or_a'] - teamxteam2['z.or_b']
teamxteam2['dr_diff'] = teamxteam2['z.dr_a'] - teamxteam2['z.dr_b']
teamxteam2['3m_diff'] = teamxteam2['z.3m_a'] - teamxteam2['z.3m_b']
teamxteam2['3a_diff'] = teamxteam2['z.3a_a'] - teamxteam2['z.3a_b']
teamxteam2['winpercintourney_diff'] = teamxteam2['winpercintourney_a'] - teamxteam2['winpercintourney_b']
teamxteam2['seed_diff'] = teamxteam2['seed_strength_a'] - teamxteam2['seed_strength_b']
teamxteam2['conf_diff'] = teamxteam2['conf_strength_a'] - teamxteam2['conf_strength_b']

In [68]:
teamxteam2.head()

,Season,team_a,team_b,team_a_win,conf_a,z.efg_a,z.sa_a,z.pt_a,rank_a,top_a,mid_a,bot_a,z.winsbefore_a,z.winsafter_a,z.clutch_a,z.close_a,z.grit_a,z.has_ot_a,z.off_a,z.def_a,z.ast_a,z.to_a,z.stl_a,z.blk_a,z.or_a,z.dr_a,z.3m_a,z.3a_a,winpercintourney_a,intourney_a,seed_strength_a,M_W_a,conf_strength_a,conf_b,z.efg_b,z.sa_b,z.pt_b,rank_b,top_b,mid_b,bot_b,z.winsbefore_b,z.winsafter_b,z.clutch_b,z.close_b,z.grit_b,z.has_ot_b,z.off_b,z.def_b,z.ast_b,z.to_b,z.stl_b,z.blk_b,z.or_b,z.dr_b,z.3m_b,z.3a_b,winpercintourney_b,intourney_b,seed_strength_b,M_W_b,conf_strength_b,efg_diff,sa_diff,pt_diff,rank_diff,winsbefore_diff,winsafter_diff,clutch_diff,close_diff,grit_diff,has_ot_diff,off_diff,def_diff,ast_diff,to_diff,stl_diff,blk_diff,or_diff,dr_diff,3m_diff,3a_diff,winpercintourney_diff,seed_diff,conf_diff
0,2022,1231,1461,1,big_ten,1.053549,-0.607257,0.755469,6,0,1,0,1.042430,-0.271965,-0.350398,1.314369,-1.182384,0.235674,0.688429,-0.201932,1.085143,-0.873188,-0.853868,1.719919,-0.810542,1.204888,-0.265326,-0.565570,0.500000,1.0,5.0,M,31.0,mwc,0.930270,-0.140585,0.839178,3,1,0,0,1.714960,0.177212,1.488742,1.102677,1.230014,1.592510,0.747340,-0.243116,-0.953000,-1.180462,-2.110188,-1.086351,-1.111711,1.467315,0.605711,0.650558,0.0,1.0,5.0,M,25.0,0.123279,-0.466673,-0.083709,3,-0.672530,-0.449176,-1.839140,0.211692,-2.412397,-1.356835,-0.058910,0.041184,2.038143,0.307274,1.256320,2.806270,0.301169,-0.262428,-0.871038,-1.216128,0.500000,0.0,6.0
1,2022,1394,1411,0,southland,0.073130,0.040983,0.384481,3,1,0,0,0.621175,0.728473,1.405460,-0.782394,-1.182384,-0.441013,1.032970,0.636364,0.380055,0.044030,0.742483,-1.532795,1.246771,-0.045570,-0.401978,-0.403002,0.000000,1.0,1.0,M,3.0,swac,0.296725,-0.358098,0.519206,3,1,0,0,0.148187,1.389988,0.489360,0.991790,1.230014,-0.417286,0.348464,-0.273772,-1.024041,0.197746,-0.936033,1.749170,0.935511,0.999543,-0.484343,-0.530129,0.5,1.0,1.0,M,1.0,-0.223596,0.399081,-0.134725,0,0.472988,-0.661514,0.916100,-1.774185,-2.412397,-0.023727,0.684506,0.910136,1.404097,-0.153717,1.678516,-3.281965,0.311260,-1.045113,0.082365,0.127126,-0.500000,0.0,2.0
2,2022,1323,1353,1,acc,1.632207,0.271003,0.684353,9,0,0,1,0.919904,0.682535,1.072333,1.220717,1.230014,-0.153197,0.756472,-0.039074,0.694953,-1.669842,-1.281732,-1.302372,-1.609499,1.159409,1.552872,0.952740,0.666667,1.0,6.0,M,28.0,big_ten,0.678785,-0.461655,0.305833,5,0,1,0,1.094163,-0.075450,0.207483,1.907498,0.023815,-0.153197,0.147626,-0.223668,1.099358,-1.128904,0.113560,0.721609,0.002911,0.148010,-0.300350,-0.564576,0.0,1.0,6.0,M,31.0,0.953422,0.732658,0.378520,4,-0.174259,0.757985,0.864850,-0.686781,1.206199,0.000000,0.608846,0.184594,-0.404406,-0.540938,-1.395293,-2.023982,-1.612410,1.011400,1.853222,1.517316,0.666667,0.0,-3.0
3,2022,1136,1460,0,nec,0.177497,1.883798,0.432286,4,0,1,0,0.473367,1.749329,0.794727,-0.427558,-1.182384,0.249939,1.435620,1.012408,0.346625,-0.207507,-0.462605,0.976943,0.843963,1.471529,1.080599,1.724247,0.000000,1.0,1.0,M,4.0,horizon,1.186001,-0.068391,0.494710,8,0,0,1,0.457449,0.850976,-0.176895,0.991790,0.000000,-1.176542,1.242073,0.724553,0.568484,-0.619111,-0.834305,-0.298402,0.021704,-0.220266,-0.153010,-0.303613,0.5,1.0,1.0,M,7.0,-1.008504,1.952189,-0.062424,-4,0.015918,0.898353,0.971621,-1.419348,-1.182384,1.426481,0.193547,0.287855,-0.221859,0.411605,0.371699,1.275345,0.822259,1.691796,1.233609,2.027859,-0.500000,0.0,-3.0
4,2022,1116,1436,1,sec,0.204001,0.545169,1.126852,3,1,0,0,1.756346,0.728473,0.031310,0.024053,1.230014,0.784870,1.512032,0.224152,0.659659,-0.619111,0.437299,0.959392,0.421182,1.143591,-0.115571,0.120142,0.750000,1.0,13.0,M,30.0,aec,2.151199,0.228052,1.865914,2,1,0,0,1.508028,1.794247,0.031310,-0.560621,-1.182384,-0.484279,1.181447,-1.060603,1.146876,-1.796202,-1.182162,-0.754535,-1.729654,1.451512,1.397191,0.936593,0.0,1.0,4.0,M,6.0,-1.947198,0.317117,-0.739062,1,0.248319,-1.065773,0.000000,0.584674,2.412397,1.269149,0.330585,1.284756,-0.487217,1.177091,1.619460,1.713927,2.150837,-0.307921,-1.512763,-0.816450,0.750000,9.0,24.0

In [69]:
teamxteam3 = teamxteam2[['Season','team_a','team_b','team_a_win','top_a','mid_a','bot_a','intourney_a',
                          'top_b','mid_b','bot_b','intourney_b',
                          'efg_diff', 'sa_diff', 'pt_diff', 'rank_diff', 'winsbefore_diff', 'winsafter_diff',
                          'clutch_diff', 'close_diff', 'grit_diff', 'has_ot_diff', 'off_diff', 'def_diff', 'ast_diff',
                          'to_diff', 'stl_diff', 'blk_diff', 'or_diff', 'dr_diff', '3m_diff', '3a_diff',
                          'seed_diff', 'conf_diff','winpercintourney_diff']]

display(teamxteam3.head(), teamxteam3.shape)

,Season,team_a,team_b,team_a_win,top_a,mid_a,bot_a,intourney_a,top_b,mid_b,bot_b,intourney_b,efg_diff,sa_diff,pt_diff,rank_diff,winsbefore_diff,winsafter_diff,clutch_diff,close_diff,grit_diff,has_ot_diff,off_diff,def_diff,ast_diff,to_diff,stl_diff,blk_diff,or_diff,dr_diff,3m_diff,3a_diff,seed_diff,conf_diff,winpercintourney_diff
0,2022,1231,1461,1,0,1,0,1.0,1,0,0,1.0,0.123279,-0.466673,-0.083709,3,-0.672530,-0.449176,-1.839140,0.211692,-2.412397,-1.356835,-0.058910,0.041184,2.038143,0.307274,1.256320,2.806270,0.301169,-0.262428,-0.871038,-1.216128,0.0,6.0,0.500000
1,2022,1394,1411,0,1,0,0,1.0,1,0,0,1.0,-0.223596,0.399081,-0.134725,0,0.472988,-0.661514,0.916100,-1.774185,-2.412397,-0.023727,0.684506,0.910136,1.404097,-0.153717,1.678516,-3.281965,0.311260,-1.045113,0.082365,0.127126,0.0,2.0,-0.500000
2,2022,1323,1353,1,0,0,1,1.0,0,1,0,1.0,0.953422,0.732658,0.378520,4,-0.174259,0.757985,0.864850,-0.686781,1.206199,0.000000,0.608846,0.184594,-0.404406,-0.540938,-1.395293,-2.023982,-1.612410,1.011400,1.853222,1.517316,0.0,-3.0,0.666667
3,2022,1136,1460,0,0,1,0,1.0,0,0,1,1.0,-1.008504,1.952189,-0.062424,-4,0.015918,0.898353,0.971621,-1.419348,-1.182384,1.426481,0.193547,0.287855,-0.221859,0.411605,0.371699,1.275345,0.822259,1.691796,1.233609,2.027859,0.0,-3.0,-0.500000
4,2022,1116,1436,1,1,0,0,1.0,1,0,0,1.0,-1.947198,0.317117,-0.739062,1,0.248319,-1.065773,0.000000,0.584674,2.412397,1.269149,0.330585,1.284756,-0.487217,1.177091,1.619460,1.713927,2.150837,-0.307921,-1.512763,-0.816450,9.0,24.0,0.750000

(44023, 35)

### Matchups and Team Stats

In [70]:
# Save merged dyad df to csv for loading in Model notebook
teamxteam3.to_csv('dyad_matchups.csv', index=False)
team_a_stats.to_csv('team_a_stats.csv', index=False)
team_b_stats.to_csv('team_b_stats.csv', index=False)